### ISSUE TITLE
App is not syncing properly

### ISSUE THREAD

**Issue by pasotrjim31** [DeFiCh/app#1051] opened 2021-10-13 04:19 UTC
I was finally able to get the update to download and sync. This took a long long time. However, I cannot see any of my investments. When I go to https://www.defichain-income.com/ I can see all my investments there, but when I open the app none of them are there and the app is on the nonresponsive side. What do I do? I really want access to my investments.

[app logs.zip](https://github.com/DeFiCh/app/files/7334811/app.logs.zip)
.

**Comment by izzycsy** [comment] 2021-10-13 09:29
Hi @pasotrjim31 , may I know what OS are you using? Is your app synced to 100%?

**Comment by izzycsy** [comment] 2021-10-14 08:35
Hi @pasotrjim31 , yes the ~0.04% more to sync is expected since the blockchain is growing daily. Can you check that your timezone on your PC is set automatically to the current time? When it syncs to 100% does your balances appear?

**Comment by pasotrjim31** [comment] 2021-10-16 21:43
OK! So, I hit the rescan button and it found all the missing addresses. 

I have a new problem now. The system won't load my dex, liquidity pairs (to add or remove), or see transactions. 

What is happening with that? 

Would you like me to send a new set of logs?

**Comment by izzycsy** [comment] 2021-10-17 19:45
Hi @pasotrjim31 , can you take a screenshot of the DEX screen? What are your environment parameters?
- DeFi Wallet Version: 
- Operating System (OS): macOS Big Sur 11.6
- Current free storage capacity:

**Comment by MichaelStaa** [comment] 2021-10-21 17:01
Did you finds a solution, because I have the same expiriense with 2.6.5. on Mac OS 11.6

**Comment by pasotrjim31** [comment] 2021-10-31 12:43
Another problem: The app sync has been stalled for a while... It has been stuck at 99.95% complete

**Comment by izzycsy** [comment] 2021-10-31 20:24
Hi @pasotrjim31 , can you save & send me your app logs again for further investigation please. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/139600074-cbf6787d-28f7-4b51-8090-988d99844b9a.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/139600077-8d879148-e112-4a46-80dd-4cbba1ed097c.png">

**Comment by izzycsy** [comment] 2021-11-01 05:40
Hi @pasotrjim31 , may I know what RAM are you operating with of your Mac? Could you a screenshot of your CPU usage?

**Comment by pasotrjim31** [comment] 2021-11-01 14:57
Getting both for you right now

**Comment by pasotrjim31** [comment] 2021-11-01 15:05
[app logs.log.zip](https://github.com/DeFiCh/app/files/7454174/app.logs.log.zip)

**Comment by pasotrjim31** [comment] 2021-11-01 15:06
<img width="827" alt="Screen Shot 2021-11-01 at 10 58 14 AM" src="https://user-images.githubusercontent.com/92419028/139693707-005f3f28-6f9e-4438-8a53-65613b591f35.png">

**Comment by pasotrjim31** [comment] 2021-11-02 04:06
<img width="2048" alt="Screen Shot 2021-11-02 at 12 01 53 AM" src="https://user-images.githubusercontent.com/92419028/139785262-f75c7ddf-0e64-499d-bc39-2f8167355f66.png">

**Comment by pasotrjim31** [comment] 2021-11-02 04:08
The app is finally sync - but there isn't any of my pools showing nor is there any of my tokens showing. 

The pic on the right is my holdings and shows you that it is still reading that the holdings are within my wallet even though the wallet doesn't show it 

How do we fix this?

**Comment by izzycsy** [comment] 2021-11-02 07:53
Hi @pasotrjim31 , please give us time to investigate. What you could do is backup your `wallet.dat`, and perhaps clear some memory in your Mac.

**Comment by izzycsy** [comment] 2021-11-03 10:27
Hi @pasotrjim31 , in the mean time, can you double check in your `defi.conf` that; 

```
spv=0
gen=0
```
<img width="735" alt="defi conf gen0" src="https://user-images.githubusercontent.com/65014479/140043672-a728e2e0-e8a4-4272-9f5b-d705b642a858.png">

If it's not, change it to 0 and save the file. Do not move the `defi.conf` out of it's original folder. 

——————————————
To find the `defi.conf` on Mac, **Go to Folder** and search: 
`/Users/username/Library/Application Support/DeFi/.defi/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/140044168-7de42acd-6969-4a76-bb6d-800e5aa014a1.png">
<img width="439" alt="Go to Folder   Defi" src="https://user-images.githubusercontent.com/65014479/140044196-9b9f1146-16c9-4610-94c7-67f7c64b4b5c.png">

**Comment by pasotrjim31** [comment] 2021-11-03 15:27
They both were on 0 - I doubled checked them :)

**Comment by thedoublejay** [comment] 2021-11-08 01:43
@pasotrjim31 can you try to type rpc `gettokenbalances` in the console from app (once synced to 100%)? And share the screenshot here

**Comment by pasotrjim31** [comment] 2021-11-08 21:49
<img width="931" alt="Screen Shot 2021-11-08 at 4 29 32 PM" src="https://user-images.githubusercontent.com/92419028/140823647-36a66701-8909-4b90-9f41-db242c4c27dd.png">
<img width="1027" alt="Screen Shot 2021-11-08 at 4 48 03 PM" src="https://user-images.githubusercontent.com/92419028/140823648-cd79897c-e490-43e8-8337-b56186d1388a.png">
<img width="1443" alt="Screen Shot 2021-11-08 at 4 48 39 PM" src="https://user-images.githubusercontent.com/92419028/140823650-7549dd81-449f-48ef-93d9-e7779302663d.png">

**Comment by pasotrjim31** [comment] 2021-11-08 21:51
I pulled up what you mentioned, but the first one didn't work. The second (minus the rpc) did. The bottom pic in black is from the Defichain website that tracks the wallet. I had set that up before the problems with the wallet.  The last two days I have tried to remove myself from the liquidity pool and try to dex my holdings so I can move them to the cake site .... I believe I tried 4 different times ... none of them worked. ...

**Comment by thedoublejay** [comment] 2021-11-09 00:11
@pasotrjim31 ok thanks for that. It seems that the issue is on display side since you have your balances just not displayed. Don't worry, your funds are safe. We'll release a test build later today, I'll let you know so you can check your funds there. Will keep you posted

**Comment by izzycsy** [comment] 2021-11-11 12:40
Hi @pasotrjim31 , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by pasotrjim31** [comment] 2021-11-13 04:03
Hey! I updated to 2.7 

Still unable to remove liquidity, dex, or anything ... It showed some numbers then all of a sudden went to all 0's again :(

**Comment by izzycsy** [comment] 2021-11-15 09:39
Hi @pasotrjim31 , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by pasotrjim31** [comment] 2021-11-18 05:40
Everything is updated and it is all showing as 0's ... Also, it shows 0 pairs ... :(

**Comment by izzycsy** [comment] 2021-11-26 07:47
Hi @pasotrjim31 , can you try updating to [v2.7.2](https://github.com/DeFiCh/app/releases/tag/v2.7.2)?

**Comment by pasotrjim31** [comment] 2021-12-03 00:20
Let me get that for you

**Comment by pasotrjim31** [comment] 2021-12-03 00:22
<img width="903" alt="Screen Shot 2021-12-02 at 7 21 39 PM" src="https://user-images.githubusercontent.com/92419028/144523602-7542905d-fc13-489a-8192-ab2f81c319c5.png">

**Comment by izzycsy** [comment] 2021-12-06 18:31
Hi @pasotrjim31 , thanks for the screenshot, the latest version currently is [v2.7.3](https://github.com/DeFiCh/app/releases/tag/v2.7.3). Can you try to update and see if you balances appear, I'm suspecting that it's due to hardware incompatibility with the desktop app; another user faced a similar issue: https://github.com/DeFiCh/app/issues/1053. If updating still does not work, you might need a better Mac. If updating to v2.7.3 works, I would suggest for you to download [DeFiChain Light Wallet](https://github.com/DeFiCh/wallet) on mobile, **create wallet**, transfer funds from desktop app to Light Wallet (since the 2 applications are built differently, you won't be able to use the same _restore wallet_ method from desktop app on mobile app).

**Comment by pasotrjim31** [comment] 2021-12-08 17:47
Currently, I am trying to sync version 2.7.3 

I will let you know if they appear.

However, I have a few questions 

1. I will save my wallet.dat  Thank you for that advice 

2. I downloaded the Light Wallet on my phone.  When I hit restore wallet, it asks me for the seed phrase - however, when I first opened the desktop wallet a year or so ago I was never given a seed phrase. I was only asked to create a sign-in password (which I did). 

Is there a way to create a seed phrase for this wallet now? So I can transfer the funds. 

In the app store there are two wallets - The first is the one requiring the seed thing 

The second is saiive.live Defichain Wallet (Defichain Light Wallet) ... 

Which one is correct?

**Comment by izzycsy** [comment] 2021-12-12 22:03
Hi @pasotrjim31 , the latest version would be [v2.8.1](https://github.com/DeFiCh/app/releases/tag/v2.8.1), you'll likely face syncing issues if you're on 2.7.3. 

Regarding _2._ the desktop app & mobile Light Wallet are not correlated when restoring wallet. Here's how you can transfer from desktop to mobile: 
1. Download DeFiChain Wallet on the [App Store](https://apps.apple.com/us/app/defichain-wallet/id1572472820) / [Play Store](https://play.google.com/store/apps/details?id=com.defichain.app)
2. **Create Wallet**
3. The mobile app will generate 24 recovery words (please **write it down** and keep it safe) & 6 digit pin for transactions purposes.
4. Once your wallet is set up on mobile, you can `send` from desktop app to your mobile app using the DeFiChain address which you have

Should you face any issues on DeFiChain Light Wallet, you mat post them here: https://github.com/DeFiCh/wallet/issues

Saiive.live is an application created by the community, you may choose to use theirs if you prefer. However, if you face issues regarding their application, you'll have to ask them instead.

**Comment by izzycsy** [comment] 2022-06-09 04:41
Hi @pasotrjim31 , update [v2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. I'll be closing this issue in the mean time. You may reopen this issue if there's new information (include screenshots) and your app logs. Thank you.

**Closed by izzycsy** 2022-06-09 04:41 UTC
Labels: needs/kind, needs/triage, os/mac
