### ISSUE TITLE
Wallet is not syncing anymore and stops after loading snapshot, showing balance 0 (new created wallet works)

### ISSUE THREAD

**Issue by dusterhub** [DeFiCh/app#1170] opened 2022-04-01 18:12 UTC
Hello there, 

I need help to figure out what happend to my wallet and how to restore it.

#### Actual behavior:
**My wallet loaded in the defi desktop app is not syncing anymore and shows balance 0 for everything (except sometimes utxo token has a balance).**
-> loading different versions of my .dat files belonging to my wallet --> sync stops with the progress of the snapshot, balance is 0
-> no wallet loaded in app --> app syncs to 100% and continues to sync
-> new created wallet loaded --> app syncs to 100% and continues to sync
-> I used the light wallet for android and loaded my wallet with my seed - worked to load but balance is 0 (but as I understood this one as normal since the desktop app and the light app are using different layers?!)

**Here is what I have done and captured with screenshots the last 2 days:**
step 1.: loaded old .dat from separate folder - screenshots 01-39
step 2.: loaded the newest .dat that was created in standard folder while loading oldest .dat from separete folder (=step 1) - screenshots 41-50
step 3.: loaded .dat from separete folder that was created in december 21 while wallet was working perfectly - december 18th 2021 - screenshots 61-68

**Here is what I have tried to restore my wallet over the last weeks:**
- Password was shown as incorrect - but I am sure to typed in the correct password since I use the passphrase to decrypt it already before the incident - the same password worked before! 
- after that the wallet was not syncing anymore
- I tried using with VPN (US, Singapore, Germany) - the wallet was not syncing
- I installed the app on an other computer and loaded the wallet - was not syncing
- I reindexed the wallet - it started syncing from 0% but it took too long to get to 100% - it synced to around 38%
- when I realized it will take too long I downloaded the snapshot within the app with the wallet loaded - the download of the snapshot always stoppt at different percentages
- after a lot of trying I managed to use VPN to download the snapshot completly (downloading snapshot works now 100% but only with vpn)
- after using the snapshot the wallet stopped syncing at the progress of the snapshot - balance of the wallet is 0
- most of the time the utxo balance will show an amount aftere some minutes with new blocks that are generated as the chain continues - but syncing stops at the last block of the snapshot
- entering the password was not showing any feedback, nothing happened
- changing the password was not possible, no feedback from the app (February 22nd 2022) - passphrase was incorrect according to the log
- sometimes the last transactions from december 2021 were displayed under the transactions tab in the app, sometimes the error "Request failed with status code 500" appeared, sometimes it just loads forever
- after exiting the wallet the app with no wallet loaded synced to 100% 
- loading a wallet.dat file the sync stops as the chain continues to generate more blocks 
- closing app with loaded wallet or exiting wallet: error 500 and 503 appears 4 times after some minutes, takes longer compared to exiting a working new wallet
- I already restarted the node and reindexed the wallet but same results after loading wallet again
- I deinstalled the desktop app and deleted (moved) the complete defichain folder - nothing changed
- I exited my wallet and generated a new one - the app loaded with this new wallet and keeps syncing to 100% - new wallet exits smoothly no errors occur

#### Expected behavior:
My wallet should sync and show the correct balance. 

#### How to reproduce it (as minimally and precisely as possible):
Find screenshots attached.

#### What are your environment parameters?
- DeFiCh/app Version: 2.9.3 (tested it with 2.9.1 as well, same results as described above)
- Operating System (OS): Windows 10 Pro, Version 1909, build 18363.1500, installed Feb 20th 2020 
– RAM (GB): 16 
– CPU (Intel Core i5/i7/etc.): AMD Ryzen 7 1700X Eight-Core Processor, 3400 MHz, 8 cores
- Current free storage capacity: 152GB

#### Anything else we need to know?
Find attached:
- app log.log
- node.log
- app config.conf
- screenshots

--> the "app log.log" contains the period of all the problems and steps mentioned above, I cut out everything before 2021-10-31 (wallet worked fine until december 2021) -- if data from before is needed let me know
--> I edited the app log file and replaced amounts with "x.xxx", addresses with numbers (1,2,3...) and passwords with "yyy".

Thank you in advance, I am glad for every help!!!

[updated Screenshots 2.12.zip](https://github.com/DeFiCh/app/files/8651698/updated.Screenshots.2.12.zip)
)

**Comment by Tomibaer** [comment] 2022-04-15 21:43
Hello support team

I have exactly the same problem with older backup files these are simply no longer synchronized! When a new walllet is created it syncs without problems however it also has no data to sync but the sync status ends successfully!

Thank you in advance, I am glad for every help!!!

@[dusterhub]
Can you please post the solution if you get an answer from support. Thanks

Hallo zusammen,
gibt es hier irgend eine lösung? wie oben beschrieben - aktualsiert sich die walltet dach dem Snap auf 100% sobald das Backup geladen wird - dann bekomme auch ich hier die sepben fehler.

I exited my wallet and generated a new one - the app loaded with this new wallet and keeps syncing to 100% - new wallet exits smoothly no errors occur

Danke im Voraus für die Unterstützung
Beste Grüß
Tom

**Comment by Tomibaer** [comment] 2022-04-22 16:42
If no one has an idea, no one can help, or no one wants to help!

**Comment by dusterhub** [comment] 2022-04-23 06:20
**Hello support team,** 

please let us know how we could help to give you the most useful information. do you need more information? do you need a shorter description? thanks in advance!

@all: has anybody an idea what could have happend to the .dat files or is the problem located somewhere else?

@all: has anybody an idea how to access the coins from another wallet / light wallet etc.?

**Comment by DomNik01** [comment] 2022-05-02 12:37
It can't be that no one from support knows a solution!
The problem can be easily reproduced by simply trying to import an old bak file.
Extra still a new notebook procured problem exists however furthermore also on the new notebook

**Comment by izzycsy** [comment] 2022-05-05 09:49
Hi @dusterhub , thanks for the detailed explanation, please give us time to investigate. 

@dusterhub @Tomibaer @DomNik01 
In the mean time, please keep a copy of your `wallets` folder + `passphrase` — keep it safe. 
To find `wallet.dat`: 

Windows — C:
`\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets `

Mac — Go to Folder: 
`/Users/<username>/Library/Application Support/Defi/wallets`

<img width="823" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/166896510-9897e8fd-42e3-4e8c-b1b3-7ff2993b1ba8.png">

If you see files named with `wallet-bak123456.dat` are also backups.

**Comment by DomNik01** [comment] 2022-05-05 16:11
DeFiCh/app Version:
DeFi Wallet v2.12.0 
Node v2.7.0

Operating System (OS):  Windows 

Windows 10 Pro
20H2
Build 19042.1682


– RAM (GB): 16.0 GB

– CPU (Intel Core i5/i7/etc.):  
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz

Current free storage capacity:

330GB free Storage


The Wallet.dat I have on a USB stick but it helps me there not, if it can no longer synchronize,
Hope you are on it that the wallet seed in the Lights wallet will work otherwise I see a big problem for my fortune,

**Comment by thedoublejay** [comment] 2022-05-06 05:36
@DomNik01 based on your last screenshots, you we're still on 2.9.3 (which will not work now due to hard fork). Can you confirm if you have these issues on the latest app version?

**Comment by dusterhub** [comment] 2022-05-06 06:28
@thedoublejay the screenshots from the original post have been created on version 2.9.3 - the latest version at that time. 
I have the same problems with the current version 2.12. I'll create a new protocol with screenshots for 2.12.

**Comment by DomNik01** [comment] 2022-05-06 16:16
Why on 2.9.3 I am on 2.12 and can not sync the old Backup,dat,

![image](https://user-images.githubusercontent.com/103442798/167171813-8c3ade7f-be97-4619-81fb-829bf3586754.png)

**Comment by DomNik01** [comment] 2022-05-06 16:33
How do I get the coins and liquidity back on a running wallet?

**Comment by thedoublejay** [comment] 2022-05-09 05:57
@DomNik01 Is it the same for 100% sync?

**Comment by DomNik01** [comment] 2022-05-09 11:06
It never synchronizes to 100% the network error comes before!
This after everything has run for 5 hours!

![image](https://user-images.githubusercontent.com/103442798/167397392-0a19cef9-d7af-4ef3-a314-901dd6523b29.png)

**Comment by dusterhub** [comment] 2022-05-09 12:44
@izzycsy  @thedoublejay  I just updated the original post with new screenshots of the 2.12 wallet version. 

Every screenshot is named with the action that happened while I was syncing the desktop app without a loaded wallet and afterwards loading my wallet with the corrupt(?) .dat file.

If the log files will help you investigating please let me know.

Thanks.

**Comment by Tomibaer** [comment] 2022-05-09 16:45
DeFiCh/app Version:
DeFi Wallet v2.12.0
Node v2.7.0

Operating System (OS): Windows Server 2019
– RAM (GB): 6 GB
– CPU AMD (with IBPB) 2.50 Ghz
Current free storage capacity: 150GB

When I load the snap then syncs wallet to 100% - As soon as I load the wallet.dat, no sync goes to 100% error messages are the same -->DomNik01
I did another try! Reset & Reindex -> Wallet sync 5 days to about 80% and does not go any further - balance is displayed but not complete  
If I now restart the wallet comes another error message and everything has to be restarted.
error
[2022-05-09 18:09:59.589] [IPC-RENDERER-error] [getBlockSyncInfo] "timeout of 5000ms exceeded"
or
[2022-05-02 17:51:49.327] [IPC-RENDERER-error]  "Network Error"
[2022-05-02 17:51:49.421] [IPC-RENDERER-error] [queueWorker] "
so the error is not solved Ahhhh 
Thanks for the support
[Log.zip](https://github.com/DeFiCh/app/files/8653637/Log.zip)

**Comment by dusterhub** [comment] 2022-05-09 19:46
@Tomibaer  "I did another try! Reset & Reindex -> Wallet sync 5 days to about 80% and does not go any further - balance is displayed but not complete"
--> I had the same process going: I was syncing from 0% without a snapshot. I started and synced until 60% or so but I decided it would take too long so I stopped. it showed the right balance at that point of the blockchain.

This seems to me that at some point at the blockchain the wallet.dat version was not valid anymore. 
Maybe there has been any event like a hard fork at that specific block? 
Could we as the user have done something wrong to generate a corrupt backup at that point? 
.. just thinking, maybe someone has an answer. 

@Tomibaer  can you tell the exact block at your 80% mark where it stopped syncing? 

I appreciate any details an knowledge about that. Thanks.

**Comment by Tomibaer** [comment] 2022-05-09 20:14
@dusterhub Block 1509410  80.79%

**Comment by ThomasKoppensteiner** [comment] 2022-05-09 20:41
My brother has the same issue with the desktop app.
As soon as he recreates the wallet (either from a backup or with the phrase) the sync stops (v2.12.0) and the wallet balance is not updated. Without an active wallet the sync works.
We tested this on Windows and MacOS.

**Comment by Rincel** [comment] 2022-05-12 18:57
I have the same problems. the problems started around January 2022. The syncronisatzion after the snapshot download became slower and slower. It took hours for the last 0.xx percent. Now it does not go on at all.

System: Win 10 Pro 21H1
16 GB RAM
120 GB Free HDD

Attempts to solve them so far:
1. uninstalled the app and deleted all folders. 
"user\xxx\.defi"
"User\xxx\Appdata\Roaming\DEFI Blockchain"
"User\xxx\Appdata\Roaming\Defi-wallet"
"User\xxx\Appdata\Local\Programs\Defi Wallet"
2. app 2.12 reinstalled
3. download snapshot and sync to 100%
4. wallet backup loaded
5. no sync
Alternatv Steps 1 and 2 Repeated and Synced without Snapshot. Sync starts and gets slower and slower. After 80 hours about 44% reached. The syncronisation was barely faster than the creation of new blocks. Therefore, I aborted it.

Translated with www.DeepL.com/Translator (free version
[Protokolle.zip](https://github.com/DeFiCh/app/files/8681844/Protokolle.zip)
)

**Comment by dusterhub** [comment] 2022-05-12 19:18
@Rincel @ThomasKoppensteiner @Tomibaer @DomNik01 
**May I ask If you have set a password for your wallet.dat?** I did it around February/March 2022. I was able to unlock the wallet after that a few times (can't tell how many days/weeks) but then it stopped syncing.  Maybe this process of setting a password could be a reason why our wallet.dat files seems to be "broken"? 

And my second question to all of you: **do you know the date/block when your wallet stopped syncing the first time?** Maybe it is the same block that all of our wallet.dat files can't sync anymore. 

Happy to hear an expert opinion from the support on this one. as well.

**Comment by Tomibaer** [comment] 2022-05-13 20:38
@dusterhub @izzycsy @thedoublejay @ThomasKoppensteiner 
I have had my password since the beginning.
And it still works now. December/January has everything worked. stopped syncing the first time?Block 150-1509365 as far as I know there was a hardforg here
Does anyone know the exact date of the hardforg?

Happy to hear an expert opinion from the support on this one as well.
Thanks in advance

**Comment by Tomibaer** [comment] 2022-05-26 06:30
Hello everyone, has anyone found a solution yet?
Happy to hear an expert opinion from the support on this one as well.
Thanks in advance

**Comment by thedoublejay** [comment] 2022-05-26 07:15
@Tomibaer which version are you using?

**Comment by thedoublejay** [comment] 2022-05-26 11:13
@dusterhub Would you mind sending your app and binary logs?

**Comment by Rincel** [comment] 2022-05-26 12:25
I set up the wallet in March 2021 and immediately secured it with a password. I have not changed it since then.
Backups of the Wallet.dat:
2021: March; August to December
2022: January and February
I have stored the wallets in different places. 

I tried the wallet from March 2021, started with a snapshot and tried the repair methods.

Result: No 100% synchronisation, but no total stop either. However, the sync ran so slowly that more new blocks were added than were synchronised.

The logs are attached.

I am now very frustrated as there have been reports of synchronisation problems for about 6 months and so far no solution has been found. If the problem is not fixed, our investments would be lost and the trust in the token and the software would suffer considerably. Maybe you could set up a trust centre and test our Wallet.dat directly. As long as they are secured with a password, no payouts would be possible, right?

Greetings Rincel

Translated with www.DeepL.com/Translator (free version
[Log Wallet 03.2021.zip](https://github.com/DeFiCh/app/files/8778906/Log.Wallet.03.2021.zip)
)

**Comment by thedoublejay** [comment] 2022-05-27 02:57
@Rincel I saw on the logs that yours just got timeout. Are you syncing from snapshot? Or from 0?

**Comment by dusterhub** [comment] 2022-05-27 10:39
@thedoublejay sure, my log files and screenshots are attached.
 
I have a lot of backup wallet.dat files as well, starting from 2021/01 to 2022/05 - no one is syncing anymore.

I downloaded a snapshot and then synced to 100% without a wallet loaded. After loading my wallet the sync stops. when loading a new created wallet the sync works fine. So same behavior as Rincel described. 

Let me know if I can support you with more information.

[app logs.zip](https://github.com/DeFiCh/app/files/8786022/app.logs.zip)

[updated Screenshots 2.12.zip](https://github.com/DeFiCh/app/files/8785978/updated.Screenshots.2.12.zip)

**Comment by ThomasKoppensteiner** [comment] 2022-05-30 06:23
@[thedoublejay](https://github.com/thedoublejay) are you already able to reproduce the bug on your side?

**Comment by Tomibaer** [comment] 2022-05-30 09:55
@thedoublejay and has anyone found a solution? or what information is still missing that we can come to a solution! thanks in advance

**Comment by DomNik01** [comment] 2022-05-30 11:13
It can not be that you can not reproduce the problem obviously we all have the same problem! Logs you find to Oberst! We would like to have a solution here!!!

**Comment by dusterhub** [comment] 2022-05-30 14:46
@thedoublejay thank you very much for your time and effort. Let me know if you need more information - we all want to find a solution to get the access to our wallets back.

**Comment by ThomasKoppensteiner** [comment] 2022-05-30 17:14
> I saw on the logs that yours just got timeout.

The logs from my brothers wallet also showed some timeouts, IIRC. (I'll ask him for some logs next weekend).
The question for me is, why does the sync sometimes timeout for recreated wallets, but not for new wallets?

Is this even an issue of the wallet software or could it be that the counterparty (some kind of node, i guess) has issues with some wallets and therefore the response takes longer as expected?

What happens after a timeout with the (network) connection? Is it reset/reopend?

**Comment by ThomasKoppensteiner** [comment] 2022-05-31 17:37
My brother just told me, that the latest version `2.13.0` might fix the issue for him.

The [comparision](https://github.com/DeFiCh/app/compare/v2.12.0...v2.13.0) to the previous versions shows, that PR #1189 is part of the new release. It changed the `SYNC_TIMEOUT` from `10000` to `30000` ([here](https://github.com/DeFiCh/app/commit/b5cfb23a014fafeb99d759758e85cf627dd17844)).
I'm not sure if this is related or not, but it sounds interesting to me.

Can someone please confirm the fix?

**Comment by thedoublejay** [comment] 2022-06-01 00:15
@ThomasKoppensteiner I don't think it's related. This syncing issue might be on the node side than the app itself. We're asking them to check it on their side

**Comment by thedoublejay** [comment] 2022-06-01 00:16
But let us know if this is fixed on the latest version @dusterhub

**Comment by dusterhub** [comment] 2022-06-01 19:59
@thedoublejay here is my update with screenshots and log files attached.
I just installed 2.13.0.

- opened desktop app with wallet loaded, syncing with wallet loaded is making some progress but at a very slow pace (started at 20:36 o'clock, 99.85%, block 1931441 of 1934340 --> current at 21:03 o'clock, 99.86%, block 1931699 of 193493 --> gain of 0.01% in 30min)
- screenshot 001 || for the first time since ~4 months I see dfi (utxo and token) and tokens balances - until 2.12.0 I have seen the utxo balance only, the rest was 0
- screenshot 004 || making slow sync progress
- screenshot 007 || transactions tab is loading and showing the last transactions from dec 21 - csv export data successfull; sync to 99.86%
- Liquidity tab still not loading as in 2.12.0
- screenshot 008 || wallet balance failure error appeared 3 times 
- screenshot 009 || after 30min of sync dfi token balance back to 0, only dfi utxo and other tokens show amounts at block 1931699 of 1934393
- screenshot 010 || transactions not loading anymore
- screenshot 011 || sync freezes at block 1931699 of 1934393 for 15min 
- screenshot 012 || sync to block 1931710 of 1934446, dfi token balance still 0, sync freezes for 25+min at this block 
I will let it sync to see if there is any more progress. after that I will reindex the wallet and load a snapshot to see if this changes anything.
- syncs to Block 1931732 of 1934509, still 99.86% at 22:00 o'clock

LOG
[logs.zip](https://github.com/DeFiCh/app/files/8818432/logs.zip)

SCREENSHOTS
[screenshots.zip](https://github.com/DeFiCh/app/files/8818436/screenshots.zip)

**Comment by DomNik01** [comment] 2022-06-06 17:56
It doesn't work yet! I can't sync my wallet since July 2021!  I also tried several backups. There is still no one who has a clue what it can be due to.

**Comment by ThomasKoppensteiner** [comment] 2022-06-07 15:09
@dusterhub please remove the `logs.zip` file. Your logs contain sensitive data!

**Comment by thedoublejay** [comment] 2022-06-10 03:00
@DomNik01 On any backups that you have, it doesn't load? Also, do you have this backup after encryption?

**Comment by DomNik01** [comment] 2022-06-13 14:29
Yes all BAckup are encrypted and can not synchronize

**Comment by dusterhub** [comment] 2022-06-20 13:50
@DomNik01 sounds great. 
Did you reindexed the wallet before you started the sync or how do you startet at 0%?
and two more questions:
How to restart a node?
How to scan for missing addresses?

**Comment by izzycsy** [comment] 2022-06-21 06:21
@DomNik01 good to hear, please backup your `wallet.dat` and keep it safe. 

@dusterhub 
To Reindex wallet (restart node): 

<img width="271" alt="Menu bar   Re-index Wallet" src="https://user-images.githubusercontent.com/65014479/174729481-9601a28f-7df1-4cda-9e25-5cbf5b304136.png">
Guide here: [Snapshot download](https://github.com/DeFiCh/app/discussions/899)

To scan for missing addresses: `Settings` > Show wallet help options > `RESCAN`

<img width="782" alt="Rescan" src="https://user-images.githubusercontent.com/65014479/174729806-d04a0389-f12f-4894-921b-46a4bc93cd08.png">

**Comment by izzycsy** [comment] 2022-06-21 06:22
@ThomasKoppensteiner @Rincel , you may try updating to [v2.14.0](https://github.com/DeFiCh/app/releases/tag/v2.14.0). Kindly `backup wallet` and read through the release notes before updating.

**Comment by ThomasKoppensteiner** [comment] 2022-06-21 07:04
> My brother just told me, that the latest version `2.13.0` might fix the issue for him.
> 
> The [comparision](https://github.com/DeFiCh/app/compare/v2.12.0...v2.13.0) to the previous versions shows, that PR #1189 is part of the new release. It changed the `SYNC_TIMEOUT` from `10000` to `30000` ([here](https://github.com/DeFiCh/app/commit/b5cfb23a014fafeb99d759758e85cf627dd17844)). I'm not sure if this is related or not, but it sounds interesting to me.
> 
> Can someone please confirm the fix?

@izzycsy for my brother the previous release [2.13.0](https://github.com/DeFiCh/app/releases/tag/v2.13.0) with the node update to version [2.8.0](https://github.com/DeFiCh/ain/releases/tag/v2.8.0) fixed the issue.
He was able to move some assets to another wallet.

**Comment by Rincel** [comment] 2022-06-21 14:02
@izzycsy Synchronisation has been working again for me since version 2.13 and with 2.14 too.

**Comment by dusterhub** [comment] 2022-06-27 13:23
Synchronisation is working for me as well. 

I will close this issue - otherwise let me know.

**Closed** 2022-06-28 00:27 UTC
Labels: kind/bug, needs/triage, os/win
