### ISSUE TITLE
DEX: something went wrong

### ISSUE THREAD

**Issue by lukefue** [DeFiCh/app#280] opened 2021-01-13 17:06 UTC
app works fine. synchronizes smoothly and balances are correct. However, when I want to use the dex it does not work I can select the pair but as soon as I type in a number it says something went wrong. and I can not press continue. When I select max. it would work. Nevertheless, when I select max. and than delete some numbers it says again  something went wrong.
![image](https://user-images.githubusercontent.com/33607469/104484880-18a2a880-55ca-11eb-8d4c-792e6f134b71.png)

**Comment by TheWeeezel** [comment] 2021-01-13 17:41
Bump! I have the same error and also can not swap anything!

**Comment by TheWeeezel** [comment] 2021-01-13 17:50
downgrade to 2.16 works

**Comment by izzycsy** [comment] 2021-01-14 13:42
Hi @lukefue , thanks for your feedback. Kindly send your app logs. This will provide more insight for the investigation. Thank you.

Hi @TheWeeezel , I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. If the issue is widespread enough you will likely see a fix in under a week's time. Thank you for your understanding.

**Comment by lraphael** [comment] 2021-01-15 10:06
I have a similar problem with the DEX. If the wallet is empty, then I can not swap. Before that, when it was not empty, it worked without problems. reported here: https://github.com/DeFiCh/app/issues/301#issuecomment-760797026

**Comment by bernd-mack** [comment] 2021-01-15 11:22
I have the same problem, when the balance of the "to" token is 0 the error described above appears. But if you transfer some ETH from e.g. Cake and the "to" balance is not 0 the DEX works fine :)

**Comment by Yannick1712** [comment] 2021-01-15 11:40
Same problem with 2.1.10

### Preflight Checklist



- [x ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.10
- **Previous DeFi App Version:**
  - 2.1.8
- **Operating System (OS):**
  - Windows 10 Home (2004)

### Actual Behavior

1. Open the app
2. Go to DEX page
3. Click on DFI left side
4. Click on e.g. BTC right side
5. If you use the "Max" Button all fine but if you type a number you get the error (if you have some tokens on the right side => e.g. BTC balance > 0 all works fine!)
6. Error: Something went wrong


### Expected Behavior
No errors

### App log / binary log / app config

[App logs 2.1.10.zip](https://github.com/DeFiCh/app/files/5820231/App.logs.2.1.10.zip)

**Comment by lraphael** [comment] 2021-01-15 11:49
If the destination wallet contains some coins, the DEX seems working: https://transfer.sh/dPLUr/Kapture%202021-01-15%20at%2012.46.36.webm

**Comment by salomonkarsten** [comment] 2021-01-15 12:16
Same problem as issue number 300

**Comment by lukefue** [comment] 2021-01-15 15:05
Here are the logs :
[binary logs something went wrong.log](https://github.com/DeFiCh/app/files/5821279/binary.logs.something.went.wrong.log)

[app logs something went wrong.log]

(https://github.com/DeFiCh/app/files/5821282/app.logs.something.went.wrong.log)

**Comment by OKnr66** [comment] 2021-01-15 22:13
Same behaviour for me in DEX swapping from DFI to Tether.

**Comment by MJDefi** [comment] 2021-01-16 11:16
I have the same problem

**Comment by PinkiNoBrain** [comment] 2021-01-16 13:26
I've worked my way around it today - tried with small amounts first!

SWAP BTC --> DFI

First choose BTC and DFI
Than choose address
Than click "max" on left side

Now you should be able to proceed to next page (button at right bottom corner)

Next page you can change the amount of BTC manually without the "something went wrong" message
I've chosen 0.0004 BTC
There is still no number visible on the DFI side

Click "Swap"


After Swap was successful, open DEX again

First choose BTC and DFI
Than choose the same address as before!!!
Than click "max" on left side

Now the amount of DFI was shown in my case and I proceed as normal.


Maybe this is going to help until the bug is fixed in a professional way...

**Comment by OKnr66** [comment] 2021-01-16 13:44
Maybe some new infos to this error. Since version 2.1.8 the Tether value is shown with zero amount, that is right, but before it was hide. Now shown with 0.00000000 . I had some in the beginning of Dezember but swaped them to DFI back. Maybe a zero value problem.

**Comment by izzycsy** [comment] 2021-01-17 09:36
Hi @Yannick1712 @lukefue @lraphael , thanks for your feedback, logs well received. Please give us time to investigate this issue. Thank you.

@bernd-mack @salomonkarsten @OKnr66 @MJDefi , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

**Comment by lezfez** [comment] 2021-01-17 11:46
https://user-images.githubusercontent.com/2002857/104839542-0ecabf00-58c2-11eb-9c79-aacce7d709f9.mov

**Comment by OKnr66** [comment] 2021-01-17 13:40
https://user-images.githubusercontent.com/76753391/104844661-cfa46a00-58d1-11eb-9303-cd14f04efddd.mp4

Here a screen movie about the problem with Tether! Thank you.

**Comment by BastianReed** [comment] 2021-01-17 18:40
i had the same error, if i want to swap DFI to BTC in the Dex.

**Comment by Sunderl4nd** [comment] 2021-01-17 19:22
> 280_v1.mov

I have exactly the same behavior.

**Comment by izzycsy** [comment] 2021-01-18 08:14
Hi @lezfez @OKnr66 , thanks for the screen recordings, could you send your app logs please? Thank you. 

Hi @BastianReed @Sunderl4nd , may I know the OS + version no. you're using? Kindly send your app logs please. Thank you.

**Comment by lezfez** [comment] 2021-01-18 08:34
all of which I have posted in issue https://github.com/DeFiCh/app/issues/319  that you have closed

**Comment by OKnr66** [comment] 2021-01-18 08:57
> Hi @lezfez @OKnr66 , thanks for the screen recordings, could you send your app logs please? Thank you.
> 
> Hi @BastianReed @Sunderl4nd , may I know the OS + version no. you're using? Kindly send your app logs please. Thank you.

Hi izzycsy, applog already sent 2 days ago. Please look above.
[Applog_2.1.10_2021-01-17.txt.log](https://github.com/DeFiCh/app/files/5828955/Applog_2.1.10_2021-01-17.txt.log)

**Comment by izzycsy** [comment] 2021-01-18 09:32
Hi @lezfez @OKnr66 , ah yes, well received. Thank you and my bad. 😅 Please give us time to investigate this.

**Comment by lezfez** [comment] 2021-01-18 09:36
> Hi @lezfez @OKnr66 , ah yes, well received. Thank you and my bad. 😅 Please give us time to investigate this.

is ok - i know you have much to to. ty for your great job

**Comment by Thovo11** [comment] 2021-01-18 12:24
Same behaviour for me in DEX swapping from DFI to BTC.
[App_log_Thomas Volk.log](https://github.com/DeFiCh/app/files/5830139/App_log_Thomas.Volk.log)

**Comment by Sunderl4nd** [comment] 2021-01-18 12:45
> Hi @lezfez @OKnr66 , thanks for the screen recordings, could you send your app logs please? Thank you.
> 
> Hi @BastianReed @Sunderl4nd , may I know the OS + version no. you're using? Kindly send your app logs please. Thank you.

[app-log.log](https://github.com/DeFiCh/app/files/5830213/app-log.log)

Im using version 2.1.0.
Thank you for your help :)

**Comment by thbestforyourbizdeployment** [comment] 2021-01-18 13:28
same here. I will wait until fix instead of downgrading

**Comment by OKnr66** [comment] 2021-01-19 14:12
Dear Support Team,

I think I have at least found a direction for the error. From my point of view it is because there are wallet levels with 0.00000000. For me it is Tether for other people it is ETH and Tether or even all three with a new account. I myself only have the issue with Tether. ETH and BTC that are not completely 0.000000 but for example 0.00034 there it goes.

With kind regards

**Comment by Yannick1712** [comment] 2021-01-22 11:02
@izzycsy 

Bug is still happening in the newest Version 2.1.11

[Logs 2.1.11.zip](https://github.com/DeFiCh/app/files/5855337/Logs.2.1.11.zip)

**Comment by TTSIP** [comment] 2021-01-22 13:20
@izzycsy 

Bug still happening @2.1.11

[Apploggs.log](https://github.com/DeFiCh/app/files/5856067/Apploggs.log)
[Binary.log](https://github.com/DeFiCh/app/files/5856068/Binary.log)

**Comment by salomonkarsten** [comment] 2021-01-22 13:44
@TTSIP Did you resync and rescan already

**Comment by TTSIP** [comment] 2021-01-22 16:26
@salomonkarsten 

resync yes 
what do you mean with rescan ?

![image](https://user-images.githubusercontent.com/76814941/105517085-e1717d00-5cd6-11eb-86ad-44fd23b7af67.png)

**Comment by lraphael** [comment] 2021-01-22 18:57
Maybe he meant ReIndex. I did ReIndex and could swap without problems afterwards. Until now I could not find any problems.
![Bildschirmfoto 2021-01-22 um 19 53 46](https://user-images.githubusercontent.com/2973257/105533079-fb698a80-5ceb-11eb-8128-d12ee2f7f4c4.png)

**Comment by TTSIP** [comment] 2021-01-22 20:44
i deinstalled the app completey and deleted all folders ... si hade to make a new sync ... but still same error

**Comment by flapdragon** [comment] 2021-01-22 23:26
I seem to be having a similar issue. I'm getting the same error in the app log anyway:
[IPC-RENDERER-error] [isBlockchainStarted] Error: Request failed with status code 500

[app-log-20210122-01.log](https://github.com/DeFiCh/app/files/5859151/app-log-20210122-01.log)
[binary-log-20210122-01.log](https://github.com/DeFiCh/app/files/5859152/binary-log-20210122-01.log)

Everything works fine except for the DEX. I can open it but once I start either typing an amount to the swap or changing the tokens in the select box it errors out with 'Something went wrong'. The error I listed about seems to happen before I do that.

Thanks.

**Comment by izzycsy** [comment] 2021-01-23 08:04
Hi @lukefue @TheWeeezel @bernd-mack @OKnr66 @MJDefi @MAKEchelon @Katakom88 @MrStryker @lezfez @Thovo11 @Sunderl4nd @thebestforyourbizdeployment @Grega-bot @Cryptopat100 , update v2.1.11 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and / or your app logs. Thank you.  

Hi @Yannick1712 @TTSIP @flapdragon , thanks for updating to v2.1.11. Logs well received, please give us time to investigate. 

Hi @lraphael , thanks for the update!

**Comment by lezfez** [comment] 2021-01-23 09:35
Great Work again!

Anything works fine.

TY

**Comment by TTSIP** [comment] 2021-01-23 15:14
2.1.2 still 
[Binary (2).zip](https://github.com/DeFiCh/app/files/5860390/Binary.2.zip)
same error

![image](https://user-images.githubusercontent.com/76814941/105603895-0c6ed600-5d96-11eb-99b0-ca2a4b5f3440.png)

**Comment by Gilli1545** [comment] 2021-01-23 21:52
2.1.12 still same problem on DEX

[Defi.zip](https://github.com/DeFiCh/app/files/5861144/Defi.zip)

**Comment by yant0r** [comment] 2021-01-24 14:36
Same issue on Linux with fresh installed 2.1.12.
[logs_and_screenshot.zip](https://github.com/DeFiCh/app/files/5862439/logs_and_screenshot.zip)

**Comment by izzycsy** [comment] 2021-01-24 17:09
Hi @TTSIP thanks for the feedback, screenshots and logs, please give us time to investigate this. 

Hi @Gilli1545 @yant0r , logs well received, please give us time to investigate this.

**Comment by sloth8871** [comment] 2021-01-26 06:32
Can report same issue as of today, tried all solutions, reindexing, etc. Any time frame on when this will be resolved?

**Comment by PrinzBG13** [comment] 2021-01-26 07:43
I have the same issue in 2.1.12, too since version 2.1.7. It always says "something went wrong"
[defi-app.log](https://github.com/DeFiCh/app/files/5871871/defi-app.log)

**Comment by izzycsy** [comment] 2021-01-26 10:36
Hi @sloth8871 , I understand your frustration, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. Can you send your logs please? Thank you. 

Hi @PrinzBG13 , logs well received.

**Comment by PrinzBG13** [comment] 2021-01-26 14:55
> Hi @sloth8871 , I understand your frustration, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. Can you send your logs please? Thank you.
> 
> Hi @PrinzBG13 , logs well received.

Version 2.1.13 fixed this issue for me! However, got a new issue now, as stated in another thread (recipient () does not refer to any valid address). I already included a current log file there. Thank you :)

**Comment by TTSIP** [comment] 2021-01-26 17:28
same for me working now but i have now the folloing issue   (recipient () does not refer to any valid address)

already posted the logs in the other thread

**Comment by yant0r** [comment] 2021-01-26 20:32
same behavior in my case: recipient () does not refer to any valid address

**Comment by eagleel** [comment] 2021-01-27 00:19
Me too same problem : recipient() does not refer to any valid address

**Comment by izzycsy** [comment] 2021-01-27 11:34
Hi @TTSIP @PrinzBG13 well noted. 

Hi @yant0r @eagleel , , update v2.1.13 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Closed** 2021-01-27 11:40 UTC
Labels: bug, first issue

**Comment by yant0r** [comment] 2021-01-27 12:40
I had the Problem with "recipient() does not refer to any valid address" on 2.1.13 but after executing the utxostoaccount command the problem was fixed.

**Comment by eagleel** [comment] 2021-01-27 20:52
I put the code line in the Console and it has solved the problem, thanks
