### ISSUE TITLE
Unable to add liquidity

### ISSUE THREAD

**Issue by mrowean** [DeFiCh/app#704] opened 2021-03-24 22:19 UTC
#### What happened:
Updated to 2.3.2
Wallets show up properly
I'm able to exchange coins / tokens on DEX

However cannot add to liquidity pools.

![please wait](https://user-images.githubusercontent.com/81331480/112390640-ffeef700-8ccc-11eb-95e3-0501dc8230d0.jpg)

please wait error shows up.

#### How to reproduce it (as minimally and precisely as possible):
Try adding to liquidity pools with new update.

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.2
- Operating System (OS): Mac OS Big Sur 11.2.3 (20D91)

#### Anything else we need to know?:

[defilogs.log](https://github.com/DeFiCh/app/files/6200795/defilogs.log)

**Comment by flapdragon** [comment] 2021-03-25 00:40
I have been having this same issue for about 3 days now. I cannot add liquidity to either DFI-USDT or DFI-BCH. I haven't tried the others. I always get the same message even though I have no pending transactions - "Please wait for your transaction to be reflected in the next block before proceeding with a new transaction."

I am on Windows 10 with app version 2.3.2.

Thanks in advance.

**Comment by dzensik** [comment] 2021-03-25 08:27
Same issue with the Version 2.3.2 on macOS BigSur 11.2.3

**Comment by izzycsy** [comment] 2021-03-25 09:51
Hi @mrowean @dzensik , thanks for your feedback. May I know which 2 tokens are you trying to pair? 

Hi @flapdragon @dzensik , thanks for your feedback, can you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/112453467-b23cc200-8d92-11eb-950e-8630210ce5a4.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/112453477-b5d04900-8d92-11eb-81e9-7ac5e51c54ca.png">

**Comment by monday24** [comment] 2021-03-25 10:05
I have the same problem. I tried to LM BTC-DFI and ETH-DFI with Version 2.3.2. and MacOS BigSur 11.2.3

**Comment by mrowean** [comment] 2021-03-25 11:08
> Hi @mrowean @dzensik , thanks for your feedback. May I know which 2 tokens are you trying to pair?
> 
> Hi @flapdragon @dzensik , thanks for your feedback, can you send your app logs please?
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/112453467-b23cc200-8d92-11eb-950e-8630210ce5a4.png">
> 
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/112453477-b5d04900-8d92-11eb-81e9-7ac5e51c54ca.png">

for me trying to add too:
USDT > DFI
LTC > DFI

**Comment by mrowean** [comment] 2021-03-25 11:36
Update: potentially solved.
I was able to add to LTC pool this morning.  
USDT pool just spins the wheel for a very long time.

Just says "Preparing UTXO
Adding liquidity"

but nothing happens --- then i reduced the amount of USDT from MAX to a even number (1.5) 
and it worked instantly.

**Comment by dzensik** [comment] 2021-03-25 11:59
@izzycsy BTC and DFI. Will provide the app logs later today

**Comment by izzycsy** [comment] 2021-03-26 08:09
Hi @mrowean , great, thanks for the update. Yes, it's suggested to leave some DFI for tx fees. To elaborate further utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via DeFi Wallet app, send DFI from your `receive address A` to your `receive address A`, the app will convert for you. 


Hi @monday24 @flapdragon @dzensik were your numbers less than MAX? if you click `MAX` DFI, in the app it gives the output automatically for you at -1. 

<img width="760" alt="Add LP   MAX -1" src="https://user-images.githubusercontent.com/65014479/112601524-85011a00-8e4d-11eb-84e2-a6220d7f2a96.png">

**Comment by mrowean** [comment] 2021-03-26 11:04
> Hi @mrowean , great, thanks for the update. Yes, it's suggested to leave some DFI for tx fees. To elaborate further utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via DeFi Wallet app, send DFI from your `receive address A` to your `receive address A`, the app will convert for you.
> 
> Hi @monday24 @flapdragon @dzensik were your numbers less than MAX? if you click `MAX` DFI, in the app it gives the output automatically for you at -1.
> 
> <img alt="Add LP MAX -1" width="760" src="https://user-images.githubusercontent.com/65014479/112601524-85011a00-8e4d-11eb-84e2-a6220d7f2a96.png">

Thank you - is there a way to convert within command? 
I only have one address - so the alternate would be to just set up a second address and send DFI there?

**Comment by izzycsy** [comment] 2021-03-26 11:14
Hi @mrowean , there's no CLI method. No need to create a new address, to convert **accountDFI** to **utxoDFI**: copy your _one_ address > Send DFI > enter amount > paste your address. Literally send to yourself.

**Comment by mrowean** [comment] 2021-03-26 11:23
> Hi @mrowean , there's no CLI method. No need to create a new address, to convert **accountDFI** to **utxoDFI**: copy your _one_ address > Send DFI > enter amount > paste your address. Literally send to yourself.

amazing - understand now thank you!

**Comment by dzensik** [comment] 2021-03-26 21:20
> were your numbers less than MAX? if you click `MAX` DFI, in the app it gives the output automatically for you at -1.
@izzycsy yes, I always leave more than 1 DFI in the wallet while I add the coin pair into the pool. However I don't use the MAX Button for DFI but for BTC, because the BTC amount is lower than the DFI amount in my wallet.
<img width="764" alt="Screenshot 2021-03-26 at 22 13 45" src="https://user-images.githubusercontent.com/6304067/112693530-1473f080-8e81-11eb-9a31-925434e6f3cd.png">

So the same issue occurs.

And also sorry I didn't get the point of you explanation about utxoDFI and accountDFI. Why do I need to convert them and where can I see the balance of these tokens?

**Comment by izzycsy** [comment] 2021-03-26 21:28
Hi @dzensik , when you use any functions in the app — send, swap, add / remove liquidity, there's a small DFI fee. This DFI is in _utxo_ form (utxo DFI). 

Say you were to add DFI-BTC to liquidity mine, and receive DeFiChain rewards. The DFI you receive in this scenario would be in _account_ form (account DFI). Now let's say you want to remove your liquidity pair and transfer it out of DeFi Wallet & back into your exchange, the accountDFI needs to be converted to utxoDFI before it can be sent out of the app. 

To check your balance, in the CLI type: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of the above commands would be the total DFI you have.

**Comment by dzensik** [comment] 2021-03-26 21:59
Hi @izzycsy and thanks for the quick help. It worked. So it seems I didn't have enough utxoDFI to pay for the fees while adding the liquidity?
My utxoDFI was 0.71673857 and accountDFI = 83.34539854@0 before I sent 1 DFI to the same address. After that the utxoDFI was 84.46324062 and accountDFI = 0.04075769@0
I don't get why the balance changes that much although I sent just 1 DFI.
Are you going to fix this behaviour in the next release?

**Comment by izzycsy** [comment] 2021-03-26 22:24
Can you try the commands again and check? if your utxo DFI is 84... it would mean that it's been converted to utxoDFI. And your issue is actually resolved. The 2 forms of DFI is not an issue. It's designed this way, but what we will do better is to educate new users on the difference. More to come in future releases.

**Comment by dzensik** [comment] 2021-03-26 22:46
This is the current status:
```
getbalance
1.03325918
gettokenbalances
[
  "3.28651598@0",
  "0.00291967@2",
  "94.07277381@5"
]
```
However I put after the accountDFI to utxoDFI conversion 83.50399831 DFI to liquidity pool.
> The 2 forms of DFI is not an issue
I meant as issue not the fact that these 2 forms of DFI exist but the issue where I have seen the balance with > 100 DFI in my wallet but was not able to put it to liquidity pool because I had only utxoDFI = 0.71673857
How is it possible?

**Comment by gosubreturn** [comment] 2021-03-27 22:15
I have the same issue.
Windows 10, Version 2.3.2 using BTC-DFI.

I have an utxoDFI of 0.52612381 DFI and cannot add Liquidity. How can I transfer DFI from the accountDFI to the utxoDFI ?

**Comment by izzycsy** [comment] 2021-03-28 09:57
Hi @dzensik , using the balance you provided, you'll need to convert 3.28651598 (accountDFI) to utxoDFI (currently 1.03325918). To convert: 
1. Copy your DeFi Wallet address 
2. Go to Send DFI
3. Amount: 3.28651598
4. Paste your address from step 1
5. Send — this will convert it to utxoDFI

You can check `getbalance` again. The app DFI balance displays the sum your utxoDFI and accountDFI. Your accountDFI balance is higher because of the rewards you receive from liquidity mining (for example). Anything you do on the app requires utxoDFI fees. 

Hi @gosubreturn , please refer to the steps above.

**Comment by dzensik** [comment] 2021-03-29 07:52
Hi @izzycsy thanks you, it works. Are you going to fix this? IMHO the DeFi Wallet users should not struggle with this because it is something that does not belong to the business case but should be solved by the app under the hood

**Comment by izzycsy** [comment] 2021-03-29 07:53
Hi @dzensik , this is not a bug, but the team will work on improve the UX for this. Thanks for your feedback!

**Comment by dzensik** [comment] 2021-03-29 07:59
@izzycsy yeah, I know this is not a bug but something that could be improved for better UX. Thanks for your help! Very appreciate!

**Comment by mat42x** [comment] 2021-04-06 08:09
I have the same problem with App v2.3.3
My balance looks like this:
`getbalances
{
  "mine": {
    "trusted": 0.99938935,
    "untrusted_pending": 0,
    "immature": 0
  }
}`

**Comment by izzycsy** [comment] 2021-04-06 11:29
Hi @mat42x , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via be DeFi Wallet app. 

  Firsty, check via CLI:  
`getbalance` — utxoDFI 
`gettokenbalances` — accountDFI  

From your output 
```
gettokenbalances
[
  "3.123456768@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Can you try to send 1 DFI to yourself:
1. copy your address (the one that you're planning to use to add liquidity)
2. send DFI
3. 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by Sumpfi-75** [comment] 2021-04-06 16:56
Hello,
i have a similar problem.

1. I did wallet update to 2.3.3, ok
2. Sent DFI to wallet, ok
3. In DEX, i changed the half of DFI in BTC, ok.
4.  I added in liquid-mining the BTC-DFI, not ok (I don't remember the error message exactly)
5.  I tryed it again, not ok (it comes the same error message as described above) 

I test the utxoDFI with getbalance. 
![DFI](https://user-images.githubusercontent.com/82049639/113748624-05a2fe80-9709-11eb-94fb-672375c43707.JPG)

The DFI and BTC are still in the wallet.
I changed 1 DFI in BTC, this gone allright, but liquid-mining doesn't work.

Help, what have I done wrong? Before i never had this problem

**Comment by BastianReed** [comment] 2021-04-12 09:35
> Hi @mat42x , it seems that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via be DeFi Wallet app.
> 
>   Firsty, check via CLI:  
> `getbalance` — utxoDFI
> `gettokenbalances` — accountDFI 
> 
> From your output
> 
> ```
> gettokenbalances
> [
>   "3.123456768@0", — accountDFI
>   "XXXXXXXXXX@2",
>   "XXXXXXXXXX@5"
> ]
> ```
> 
> Can you try to send 1 DFI to yourself:
> 
> 1. copy your address (the one that you're planning to use to add liquidity)
> 2. send DFI
> 3. 1 DFI
> 4. Paste the address
> 5. Try the function again
> 
> By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

Hello Izzy, i have the same Problem. 
if i send me 1 DFI from my wallet to me, it works for one transaction. After that the same issue exists furthermore...

**Comment by izzycsy** [comment] 2021-04-12 10:31
Hi @BastianReed , can you send more to yourself then? You can check where the DFI are located in the respective address and send to the address lacking DFI. 

`listaccounts {} false false true` 
— breakdown of your token(s) & addresses

**Comment by BastianReed** [comment] 2021-04-12 11:06
> listaccounts {} false false true

no, same issue after i send 5 dfi on my address. 
only one transaction is possible before the error comes again.

**Comment by izzycsy** [comment] 2021-04-12 11:43
Hi @BastianReed , can you provide the output of `listaccounts {} false false true` so I can understand the issue further. You can change the strings to xxx, I'll provide an example below: 

```
{
    "key": "a914xxx@0",
    "owner": "dTmhxxx",
    "amount": "0.00007548@DFI"
  },
  {
    "key": "a914xxx@1",
    "owner": "dTmhxxx",
    "amount": "0.00000016@DFI-ETH"
  },
  {
    "key": "a914xxx7@2",
    "owner": "8JaZxxx",
    "amount": "0.00000071@DFI"
  }
```

**Comment by BastianReed** [comment] 2021-04-12 14:32
> Hi @BastianReed , can you provide the output of `listaccounts {} false false true` so I can understand the issue further. You can change the strings to xxx, I'll provide an example below:
> 
> ```
> {
>     "key": "a914xxx@0",
>     "owner": "dTmhxxx",
>     "amount": "0.00007548@DFI"
>   },
>   {
>     "key": "a914xxx@1",
>     "owner": "dTmhxxx",
>     "amount": "0.00000016@DFI-ETH"
>   },
>   {
>     "key": "a914xxx7@2",
>     "owner": "8JaZxxx",
>     "amount": "0.00000071@DFI"
>   }
> ```

Here is my output with anonym the strings:

listaccounts {} false false true
[
  {
    "key": "a9145xxxx@0“,
    "owner": "dMsfWCxxx“x,
    "amount": "9.05545701@DFI"
  },
  {
    "key": "a9145cxxxx“,
    "owner": "dMsfxxxx“,
    "amount": "0.00000047@BTC"
  },
  {
    "key": "a9145cbxxxxx@5“,
    "owner": "dMsfxxx“x,
    "amount": "80.11162198@BTC-DFI"
  },
  {
    "key": "76a91xxxx“x,
    "owner": "8F6uxxxx“x,
    "amount": "2.47026237@DFI"
  },
  {
    "key": "76a91xxxxx@1“,
    "owner": "8F6xxxx“,
    "amount": "0.00000500@ETH"
  },
  {
    "key": "76a91xxxx@2“,
    "owner": "8F6uxxxx“,
    "amount": "0.00048432@BTC"
  },
  {
    "key": "76a9xxxx@4“,
    "owner": "8F6xxxx“,
    "amount": "14.69841921@ETH-DFI"
  },
  {
    "key": "76a91xxxxx@5“,
    "owner": "8F6xxx“x,
    "amount": "19.06834440@BTC-DFI"
  },
  {
    "key": "76a914xxxxx@0“,
    "owner": "8Hnxxxx“,
    "amount": "16.85091111@DFI"
  },
  {
    "key": "76a9xxxx@2“,
    "owner": "8Hnpxxxxx“,
    "amount": "0.00000045@BTC"
  },
  {
    "key": "76a91xxxx@5“,
    "owner": "8Hnxxxx“x,
    "amount": "77.43746587@BTC-DFI"

**Comment by izzycsy** [comment] 2021-04-13 10:46
Hi @BastianReed , thank you. From your output, these are your addresses with DFI (both in utxoDFI & accountDFI form). I'll use one of the addresses for the example to convert your accountDFI to utxoDFI. 

```
{
"key": "a9145xxxx@0“,
"owner": "dMsfWCxxx“x,
"amount": "9.05545701@DFI"
},
{
"key": "76a91xxxx“x,
"owner": "8F6uxxxx“x,
"amount": "2.47026237@DFI"
},
{
"key": "76a914xxxxx@0“,
"owner": "8Hnxxxx“,
"amount": "16.85091111@DFI"
},
```

To send 1 DFI to yourself:
1. copy your address `a9145xxxx`
2. Go to send DFI
3. Amount input: 1 DFI
4. Paste the address `a9145xxxx`
<img width="785" alt="Screenshot 2021-04-13 at 6 45 51 PM" src="https://user-images.githubusercontent.com/65014479/114540754-7fe2fe00-9c88-11eb-9453-fdf807b55a27.png">

5. Try the function again (DEX / add liquidity / remove liquidity)

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees, hence you always need a balance of it.

**Comment by BastianReed** [comment] 2021-04-13 14:43
> Hi @BastianReed , thank you. From your output, these are your addresses with DFI (both in utxoDFI & accountDFI form). I'll use one of the addresses for the example to convert your accountDFI to utxoDFI.
> 
> ```
> {
> "key": "a9145xxxx@0“,
> "owner": "dMsfWCxxx“x,
> "amount": "9.05545701@DFI"
> },
> {
> "key": "76a91xxxx“x,
> "owner": "8F6uxxxx“x,
> "amount": "2.47026237@DFI"
> },
> {
> "key": "76a914xxxxx@0“,
> "owner": "8Hnxxxx“,
> "amount": "16.85091111@DFI"
> },
> ```
> 
> To send 1 DFI to yourself:
> 
> 1. copy your address `a9145xxxx`
> 2. Go to send DFI
> 3. Amount input: 1 DFI
> 4. Paste the address `a9145xxxx`
> 
> <img alt="Screenshot 2021-04-13 at 6 45 51 PM" width="785" src="https://user-images.githubusercontent.com/65014479/114540754-7fe2fe00-9c88-11eb-9453-fdf807b55a27.png">
> 
> 1. Try the function again (DEX / add liquidity / remove liquidity)
> 
> By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees, hence you always need a balance of it.

Hello izzy, 
i think you mean to send not to the string after "key" rather to the owner Adress on the a9145 key.
this i what i do in the past but it will work only one transaction after the error comes again...

**Comment by izzycsy** [comment] 2021-04-14 10:01
Hi @BastianReed , ah yes, my bad, send to your own address. Your balance for utxoDFI must always have a minimum of 1 so that the function you want to perform gets through. It does not work the 2nd time probably due to a lack of it, meaning most of your DFI are in accountDFI form — those that you receive from liquidity mining rewards. So you need to convert them. Maybe try converting a higher number or MAX?

**Comment by BastianReed** [comment] 2021-04-14 16:02
> Hi @BastianReed , ah yes thank you, my bad, send to your own address. I've updated my comment to prevent confusion. Your balance for utxoDFI must always have a minimum of 1 so that the function you want to perform gets through. It does not work the 2nd time probably due to a lack of it, meaning most of your DFI are in accountDFI form — those that you receive from liquidity mining rewards. So you need to convert them. Maybe try converting a higher number or MAX?

Now i make this with 5 DFI. Same issue. 
Where i can convert a higher number of accountDFI to utxoDFI?

**Comment by izzycsy** [comment] 2021-04-15 08:49
Hi @BastianReed you can click on `MAX`.

**Comment by BastianReed** [comment] 2021-04-15 10:07
OK thanks izzy, two transactions work after i click max DFI. 
i will observe these. 

Best Greetings
Bastian

**Comment by BastianReed** [comment] 2021-04-20 06:47
> Hi @BastianReed you can click on `MAX`.

Hello Izzy, i have reviewed these over time. 
The Problem exists furthermore i click on max and transfer over 30 DFI...

I must transfer every time 1 dfi to my address and then, a second transaction works...

**Comment by izzycsy** [comment] 2021-04-20 08:29
Hi @BastianReed I understand, from your balance provided previously, 9.05545701 + 2.47026237 + 16.85091111 = `28.37663049` DFI — less than 30 DFI. Meaning the MAX you can add liquidity / DEX would be `27.37663049` DFI before the utxoDFI becomes insufficient. 

Alternatively a quicker way to check your balance, in the CLI type: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total DFI tokens. 

Hence, a good rule of thumb (if you're planning to use MAX) would be `MAX -1` when performing any transaction. We'll be implementing `MAX -1` in [future releases](https://github.com/DeFiCh/app/issues/686), as well as an improvement to the UX for utxoDFI & accountDFI, till then thank you for your understanding.

**Comment by BastianReed** [comment] 2021-04-20 08:48
> Hi @BastianReed I understand, from your balance provided previously, 9.05545701 + 2.47026237 + 16.85091111 = `28.37663049` DFI — less than 30 DFI. Meaning the MAX you can add liquidity / DEX would be `27.37663049` DFI before the utxoDFI becomes insufficient.
> 
> Alternatively a quicker way to check your balance, in the CLI type:
> `getbalance` — utxoDFI
> `gettokenbalances` — accountDFI
> 
> The sum of utxoDFI & accountDFI would be your total DFI tokens.
> 
> Hence, a good rule of thumb (if you're planning to use MAX) would be `MAX -1` when performing any transaction. We'll be implementing `MAX -1` in [future releases](https://github.com/DeFiCh/app/issues/686), as well as an improvement to the UX for utxoDFI & accountDFI, till then thank you for your understanding.

Ok thanks, i will wait of the new release and hope it will work better with the utxoDFI and accountdfi balance.

**Comment by Kevinwhits** [comment] 2021-05-06 23:26
Thanks for your help Izzy! 

I tried to transfer 1 DFI to "all" my wallets and still get the error message. 

"Insufficient UTXO DFI for transaction fees. Please send some DFI from an exchange or another wallet and try again."

I have no idea what to do...Here are my balances...

getbalance
0.00008474
gettokenbalances
[
  "179.82517718@0",

Any Ideas I could try?

**Comment by izzycsy** [comment] 2021-05-07 09:28
Hi @Kevinwhits , insufficient utxoDFI balance (min. 1 DFI) — is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would be via DeFi Wallet app.   

Thanks for the output, here's the solution: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI 

From your output 
```
gettokenbalances
[
  "179.82517718@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Send 1 accountDFI to yourself:
1. copy your address (the one that you're planning to use to add liquidity)
2. Click `send DFI`
3. Input 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.
Our team is working on improving the UX for this. Thank you.

**Comment by izzycsy** [comment] 2021-05-12 05:12
Hi @stevievol , DFI exist in 2 forms; `utxoDFI` and `tokenDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in tokenDFI. The above instructions is how to convert your tokenDFI to utxoDFI.

**Comment by Kevinwhits** [comment] 2021-05-13 10:09
Hi Stevievol. 

I wasn't able to transfer 1 token DFI to 1 utxo DFI. 

What did work for me was buying DFI from Cake. Then send the DFI to Defi chain and use that for liquidity mining, Dex and transferring coins to cake. 

When I did make a transaction happen on Defi Chain the balance went down by 0.1. 

getbalance
4.80012652
getbalance
4.79919134

Just remember to leave some DFI on the blockchain to make transactions happen.  Hope this helps.

**Comment by izzycsy** [comment] 2021-05-28 11:12
Hi @mrowean @dzensik @ideolog @mat42x @flapdragon @monday24 @gosubreturn @BastianReed @Kevinwhits @stevievol [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment] 2021-06-02 13:02
Hi @mrowean @dzensik @ideolog @mat42x @flapdragon @monday24 @gosubreturn @BastianReed @Kevinwhits @stevievol @778010 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment] 2021-06-14 20:07
Hi @mrowean @dzensik @ideolog @mat42x @flapdragon @monday24 @gosubreturn @BastianReed @Kevinwhits @stevievol @778010 , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. If your issue persist, you may open a new ticket. Thank you.

**Closed by izzycsy** 2021-06-14 20:07 UTC
Labels: kind/bug, os/mac, triage/accepted, version/2.3.2
