### ISSUE TITLE
DefiChain Desktop Wallet not recognizing BTC

### ISSUE THREAD

**Issue by everlast556** [DeFiCh/app#1199] opened 2022-05-16 13:35 UTC
Overview:

Using the desktop wallet, I deposited some DFI and BTC. Both show correctly in my balances screen. The DFI seems to work correctly throughout. However, BTC doesn't seem to be recognized anywhere else in the wallet. Either selection is missing or balance shows as 0.00.

#### Actual behavior:

- When going to the DEX screen, BTC balance shows as zero.
- Going to liquidity screen to add liquidity to btc-dfi pair, BTC selection doesnt even show.
- In transaction screen, only DFI transaction is listed, not BTC.
- When checking the wallet address for BTC created by the DFI desktop wallet, it says it can't be found: https://defiscan.live/address/bc1q7c2g0znk7hyy8q59cyj2l97c8c3dd0jxt0sxc6
- Even though the transaction is shown on BTC blockchain: https://tradeblock.com/bitcoin/address/bc1q7c2g0znk7hyy8q59cyj2l97c8c3dd0jxt0sxc6
- Tried to withdraw BTC from wallet and it shows amount on the screen but when I try to actually send it, says insufficient funds. Probably because it thinks the balance is zero.

#### Expected behavior:
BTC to be recognized throughout wallet and balance to be shown and used correctly.

#### How to reproduce it (as minimally and precisely as possible):
Deposit some amount of BTC to DeFiChain wallet. Try to use it on DEX or liquidity screens.

#### What are your environment parameters?

- DeFiCh/app Version: 2.12.0
- Operating System (OS): Windows 10
– RAM (GB): 16
– CPU (Intel Core i5/i7/etc.): Ryzen 7 
- Current free storage capacity: enough

[logs.zip](https://github.com/DeFiCh/app/files/8700421/logs.zip)
![dfi 1](https://user-images.githubusercontent.com/54565405/168604784-d55a1475-e9dc-4cbd-a4f8-5842e82222f6.png)
![dfi 2](https://user-images.githubusercontent.com/54565405/168604788-9ac9b0e3-2d31-4b2e-9202-f3e6d93c1ca5.png)
![dfi 3](https://user-images.githubusercontent.com/54565405/168604790-e61bdc26-4785-492c-8399-30565c4695a0.png)
![dfi 4](https://user-images.githubusercontent.com/54565405/168604791-f904bce4-d9f1-48dc-9a2b-53988aae9948.png)
![dfi 5](https://user-images.githubusercontent.com/54565405/168604792-ec45013d-46f3-4525-b24c-0746dd1cfd7f.png)

**Comment by izzycsy** [comment] 2022-05-20 03:35
Hi @everlast556 , the reason why you don't see your BTC on DEX or on DeFiScan is because for native BTC being sent to DeFiChain desktop app, it can only be for send (to and fro from your BTC address on BTC Network). The address that you created to receive / send BTC `bc1q` is a Bitcoin Network address, hence also why you're able to view the transaction on the Bitcoin Explorer instead. 

If you would like to use the other features; on DeFiChain Network, you'll have to send DFI instead. To send DFI, you may do so from exchanges which supports DFI via DeFiChain Network — KuCoin, Bittrex, Hotbit just to name a few. 

Closing this thread as it's not a bug, if you've further enquires on how to use DeFiChain Desktop app, you may do so on [DeFiChain Telegram (EN)](https://t.me/defiblockchain).

**Closed by izzycsy** 2022-05-20 03:35 UTC
Labels: kind/bug, needs/triage, os/win

**Comment by everlast556** [comment] 2022-05-20 04:09
Why are there selections for BTC in the DEX than? Why does no transactions show for BTC when it accepts it? How can you add BTC liquidity to a BTC/DFI pair without BTC? Why can I not withdraw the BTC then? If these aren't bugs, surely you can see there are some serious UI issues here.

**Comment by Sigibret** [comment] 2022-07-26 01:32
I have the same problem as described above. Why I can't use this BTCs ? - I sent my BTCs from Cake to DEFICHAIN and now I can't do anything with it. How can I recover them then ?  Would be great to get any help about this.   I was sending the BTCs to add liquidity in the BTC-DFI pair but the BTCs are not recognized.  And how can I use my BTS now? or what is to do?  
It seems to be the same problem as  [everlast556](https://github.com/everlast556)   has

**Comment by Sigibret** [comment] 2022-07-26 21:32
However, it would be great, if anyone can solve this problem in the future. The BTCs sent to the wallet, are not useful for anything then sending them back. 
If you send DFI and change them into BTC on the DEX, these dBTC you can use for liquidity pools.  (BTC-DFI - for example) But it is very, very confusing as it is made now!   If there is an intention, that people use this DEFICHAIN, it should be much more easy to handle.
