### ISSUE TITLE
App is not showing any rewards

### ISSUE THREAD

**Issue by nico89-exp** [DeFiCh/app#1014] opened 2021-08-05 15:21 UTC
#### Actual behavior: 
When switching to Transaciotns tag, checking "Include Rewards" doesn't show any rewards. Only transactions are shown. Also the export is not containing rewards.

#### Expected behavior:
Rewards and Commisions should be shown and also exported. This worked in 2.5.2

#### How to reproduce it (as minimally and precisely as possible):
cf. above

#### What are your environment parameters?

- DeFi Wallet Version: 2.6.0
- Operating System (OS): Win
- Current free storage capacity: >500GB

**Comment by nico89-exp** [comment] 2021-08-06 09:43
Tested also on Linux -> same issue

CLI with listaccount address command exports correctly.

**Comment by izzycsy** [comment] 2021-08-09 04:07
Hi @nico89-exp , thanks for your feedback, could you kindly send your logs for investigation please? Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/128659476-a9627f34-395e-4fe5-bdfb-82116786b92e.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/128659484-7341438f-168d-43f1-ad19-e7e9623b251e.png">

**Comment by izzycsy** [comment] 2021-08-12 18:35
Hi @nico89-exp , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. This comment is to notify you about the update.

**Comment by chk-** [comment] 2021-08-15 13:25
I am also affected, but not since the update to v2.6.0 or v2.6.1, but since I disbanded and reorganized my LM.

**Comment by izzycsy** [comment] 2021-08-15 20:05
Hi @chk- , rewards would be shown under the DFI tab; since rewards are given out in DFI. If your rewards are not shown after checking `Include Rewards`, please take a screenshot & send your logs for investigation. Thank you. 

<img width="776" alt="Include reward tx" src="https://user-images.githubusercontent.com/65014479/129491184-c4176580-1f1f-4aa3-9f40-5bb0003555b5.png">

**Comment by chk-** [comment] 2021-08-16 12:23
Hi @izzycsy, I can confirm that I checked the "Include reward transactions" checkbox.

I would suggest checking in the source code whether all DFI addresses are queried during the export and not just the initial / primary address.
I don't have a setup for debugging right now, but I guess the part in DeFiCh/app/webapp/src/containers/TransactionsPage/service.tsx: 481 would be a good breakpoint.

**Comment by chk-** [comment] 2021-08-16 14:42
Hi @izzycsy, in addition, I share my experiences as follows.

These steps reproduce the problem:
1.) Create a wallet with standard values ​​(1 DFI address @mydfi)
2.) Creation of an LM pool BTC-DFI (rewards to the address @mydfi)
3.) Creation of a LM pool ETH-DFI (rewards to the address @mydfi)

Result when exporting including rewards: All rewards available.

4.) Create 2 DFI addresses: @mydfibtc, @mydfieth
5.) Dissolve the two LM pools
6.) Creation of an LM pool BTC-DFI (rewards to the address @mydfibtc)
7.) Creation of a LM pool ETH-DFI (rewards to the address @mydfieth)

Result when exporting including rewards: No more new rewards available.

8.) Dissolve the two LM pools
6.) Creation of an LM pool BTC-DFI (rewards to the address @mydfi)
7.) Creation of a LM pool ETH-DFI (rewards to the address @mydfi)

Result when exporting including rewards: All rewards available.

Summary of the status:
At first everything worked with just one DFI address. As soon as several DFI addresses were configured for the LM pools, the export function no longer fetched the new rewards, but all previously historical rewards were available. After the LM pools were set up again to the original DFI address, all rewards from all addresses were in the export again.

**Comment by memzila** [comment] 2021-08-17 06:54
Thanks @chk- for this detailed analysis. This issue is open since several months. I have similar issues because i have startet with multiple addresses and have moved all to only one address.
Long it was that i had not seen rewards since the move to one address. After some recent version it is the other way around. I don’t see rewards older than the move to one address.

**Comment by izzycsy** [comment] 2021-08-17 07:26
Thanks @chk- @memzila , the team will look into the issue. Could you save and send your logs please, it'll help with the investigation. Thank you.

**Comment by memzila** [comment] 2021-08-17 08:20
First the synching problems need to be fixed before i can normaly work with the wallet again. I have currently the other known issue with the very slow synching

**Comment by izzycsy** [comment] 2021-08-18 04:54
Hi @chk- @memzila , update [v2.6.2](https://github.com/DeFiCh/app/releases/tag/v2.6.2) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by memzila** [comment] 2021-08-18 13:06
Hi @chk- . Have you tested with newest version already? Probably they have fixed it finaly. At least i see older rewards now in the export than when i have all moved to one address.

**Comment by chk-** [comment] 2021-08-18 17:14
Hi, everyone,

I just upgraded from v2.6.1 to v2.6.2. So far everything is going as usual.
@izzycsy regarding the transmission of my logs, I have concerns about possibly disclosing personal data.

My current status is that I have reconfigured to only one DFI address and therefore cannot say whether v2.6.2 can solve the problem. I don't want to change that either. However, I assume that the problem can be reconstructed from my and other descriptions.

I hope this is okay with you.

The reason why I wanted to use several DFI addresses is to be able to display the rewards for each pool separately. (A must) When I discovered that this was already possible through the poolID in the data set, I no longer saw any reason for multiple DFI addresses. Otherwise it would also be possible to operate several wallets. What is the reason for having multiple addresses in the wallet? The question is not meant to be suggestive, but I ask for an answer in order to be able to build understanding.

**Comment by izzycsy** [comment] 2021-08-19 09:17
Hi @chk- , thanks for sharing your experience, unfortunately we're unable to reproduce it, and in such cases the app logs will be useful for investigation. The app logs does not contain information with others can use, it's for the purpose of when a user faces an issue and we can further understand and try to resolve it. I understand that you've concerns sending it, so it's fine. The workaround would be as you mentioned 1–3, use 1 DFI address. And also doing a reindex, which in your case won't be necessary since your issue has been resolved by having 1 DFI address. There are a few reasons for having multiple addresses feature on the app, such as due to user demand & for those running a masternode. On that note, I'll be closing this issue for now, if you've new information, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Closed by izzycsy** 2021-08-19 09:17 UTC
Labels: kind/bug, needs/triage, os/win, version/2.6.0

**Comment by nico89-exp** [comment] 2021-08-19 10:00
I checked this with 2.6.2 and now all rewards are shown (both pools I use) and also exported properly. Thanks!
