### ISSUE TITLE
Can not see my wallet

### ISSUE THREAD

**Issue by crypto-uli** [DeFiCh/app#163] opened 2020-12-22 20:06 UTC
All,
there are already similar posts, but I want to describe here in detail my issue.
I have The DeFi app Version 2,1,3 Installed on Windows 10
When I start syncronizing works and the liquidity is displayed correctly.
My wallet can not be seen, 
I have a Wallet backup but I can not import.
 I can not Restore ( I have my Memonic Seed). I I do so, the programm says to start the applickation new, but the start does not work.

I tried to exchange the wallet.dat file but didn´t work.

Do you know meanwhile a solution for this?
Thanks in advance. For you support an effort.

**Comment by crypto-uli** [comment] 2020-12-22 20:46
Find here my logfiles
the config filed hase been ranamed to .txt
the app log and the binary log are not complete due to file size limitation. I erased the first part.
[app-config.txt](https://github.com/DeFiCh/app/files/5731881/app-config.txt)
[app-log3.log](https://github.com/DeFiCh/app/files/5731899/app-log3.log)
[binary-log3.log](https://github.com/DeFiCh/app/files/5731925/binary-log3.log)

Regarsd Uli

**Comment by izzycsy** [comment] 2020-12-23 07:30
Hi @crypto-uli , thanks for your feedback. What does your screen show when your wallets cannot be seen? Do you have a screenshot? Please give us time to investigate this.

**Comment by crypto-uli** [comment] 2020-12-23 11:08
![grafik](https://user-images.githubusercontent.com/76495398/102990267-6110fe00-4517-11eb-82b4-628cc9aea8ca.png)

find here the screenshot of my wallet.

**Comment by izzycsy** [comment] 2020-12-24 08:30
Thanks @crypto-uli . Please give us time to investigate this.

**Comment by izzycsy** [comment] 2020-12-24 11:23
Hi @crypto-uli , may I know if the issue is resolved with the new update v2.1.4?
https://github.com/DeFiCh/app/releases/tag/v2.1.4

**Comment by crypto-uli** [comment] 2020-12-24 16:10
Hi izzycsy,
I did an update to v2.1.4
But no change, Liquiditiy and DEX are visible and wirking, but wallets are not visible.
Furter, like peviously I,m not able to recreate my wallet by using the Memonic seed.
When I do so It get stuck. "restart Node" will not finish.
See this screenshot.
![grafik](https://user-images.githubusercontent.com/76495398/103098380-d5789980-460a-11eb-9697-0ea59889b8a7.png)

**Comment by izzycsy** [comment] 2020-12-26 10:10
Hi @crypto-uli , could you send your app log again please? Thank you. 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103149569-9763ad00-47a5-11eb-9070-d38107d5d312.png">
<img width="511" alt="2 Komprimiere" src="https://user-images.githubusercontent.com/65014479/103149565-9468bc80-47a5-11eb-8df0-2351c7575369.png">

**Comment by jdavidhuebner** [comment] 2020-12-28 16:46
I'm sure this comment does not help that much - but I have exactly the same Issue. Even tried downgrading to 2.13 again, as written in another thread. If it helps, I'll provide screenshots or logs.

**Comment by crypto-uli** [comment] 2020-12-28 19:44
@ izzycsy
after shut down the computer, waiting 3 days during chrismas, it worked today.
I was alble to restore the wallets with my mnemonic Seed.
Wallets are visible now even with the correct amount of coins.
But I have now another problem: I can not add liquidity anymore, since there is no valid adress for the transaction.
I Will open another issue for that. I you know a solution for this, please let me know
**This issue can be closed**, at least from my side. But as you can see I´m not the only one facing such problems.
Regards and thanks for your support

@jdavidhuebner
I have basically no precise advice for you.
I have version 2.1.4
as mentioned just waited 3 days, started again and restored my wallet.
What is important:
wait until the blockchain is completely syncronized.
Give the system sufficient time to process each command.
Otherwise I can not explain why it works now.

**Comment by izzycsy** [comment] 2020-12-29 08:29
@crypto-uli I will leave this thread open. Could you still send your app logs please? It'll help the team with the investigation. Thank you!

**Comment by izzycsy** [comment] 2020-12-29 08:30
@jdavidhuebner if you're facing a similar issue, please send screenshots & your app logs. Thank you.

**Comment by izzycsy** [comment] 2021-01-11 16:32
Hi @jdavidhuebner , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Closed by izzycsy** 2021-01-11 16:32 UTC
Labels: bug, fixing, need logs
