### ISSUE TITLE
"Error occurred while sending amount"

### ISSUE THREAD

**Issue by UserMaxL** [DeFiCh/app#81] opened 2020-12-02 23:19 UTC
Dear Dev-Team,

I'm not able to send DFI from the DeFi Chain App.
The error massage is "Error occurred while sending amount".

Log files attached.

Thanks,
Max

[app_log.log](https://github.com/DeFiCh/app/files/5632603/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5632604/binary_log.log)

[app_config.zip](https://github.com/DeFiCh/app/files/5632623/app_config.zip)

**Comment by muelln** [comment] 2020-12-03 06:40
Same with me.

[app_log.log](https://github.com/DeFiCh/app/files/5634129/app_log.log)
[binary_log.log](https://github.com/DeFiCh/app/files/5634130/binary_log.log)
[app_config.conf.conf.zip](https://github.com/DeFiCh/app/files/5634131/app_config.conf.conf.zip)

**Comment by izzycsy** [comment] 2020-12-03 07:24
Hi @UserMaxL & @muelln , thanks for your feedback. We're currently addressing the "unable to send DFI" issue, in the mean time, please update your app to v2.1.1 if you have not <https://github.com/DeFiCh/app/releases/tag/v2.1.1>.

**Comment by muelln** [comment] 2020-12-03 12:37
Hi @izzycsy 
updated recently to new version v2.1.2 and its still not solved

**Comment by izzycsy** [comment] 2020-12-03 12:57
@muelln I see, may I know what OS you're using? Could you describe your user flow more? Are you on Mainnet / Testnet? We need more details in order investigate how to reproduce this issue. Thank you!

**Comment by muelln** [comment] 2020-12-03 13:14
@izzycsy I am using HighSierra 10.13.6. I am in the Mainnet. I simply go to my wallet, chose the DFI coin-->send-->enter quantity and address--> confirm then deposit after 5sec, some seconds later the error message is coming. 

Nevetheless I see from time to time multiply entries of transactions (eg 051828b8e27a403ce261e5af814e3ef819a66300c1572deff9cd7763dd3802f9).
They are always displayed two times and are basically connected to the trials of sending DFI to cake

Hope that helps
![screenshot transaction2](https://user-images.githubusercontent.com/75412912/101022517-c9506d80-3571-11eb-9d58-7c48a56882b4.png)

**Comment by UserMaxL** [comment] 2020-12-03 14:26
I'm on the Mainnet too and running on Windows 10 Enterprise.
One hint. In the German Defi Chain telegram chat it seems this is related to the fact that not all DFI are real DFI, but there are kind of wrapped DFI which can't be sent. Those "wrapped" DFI are coming from the Pool or from the DEX. Putting "GetBalance" in the CL gives me a much lower DFI vs. what I actually have.

**Comment by muelln** [comment] 2020-12-03 14:40
@izzycsy update to 2.1.3 does not help too

**Comment by UserMaxL** [comment] 2020-12-03 14:45
No, same issue on 2.1.3 unfortunately.

**Comment by izzycsy** [comment] 2020-12-03 15:16
@muelln @UserMaxL i see, thank you for elaborating. Let us investigate this, thank you for your understanding.

**Comment by hielscher92** [comment] 2020-12-03 16:54
Hi same problem at me in main net with windows 10

**Comment by muelln** [comment] 2020-12-04 14:51
@izzycsy  Sorry for putting pressure but I need to know when I can sent again DFI from DefiChain-App to Cake. I need to move some coins and it is frustrating that my assets are captured and not movable. Maybe there is a workaround I could try, instead of using the app - but please tell me

**Comment by izzycsy** [comment] 2020-12-04 16:31
@muelln I understand your frustration, we're still investigating this issue, please give us some time. Thank you for your understanding.

**Comment by UserMaxL** [comment] 2020-12-04 20:57
Have you been able to reproduce the issue?

**Comment by DanielHirsbrunner** [comment] 2020-12-05 19:00
Same problem here. Windows 10 Wallet 2.1.3. The explanation of @UserMaxL would also match my case, i swapped usdt for dfi and try to send these. In Fiddler I see, that when the wallet is executing the post request to 127.0.0.1:8555 for the sendtoaddress method, I get a 500 and the response "{"result":null,"error":{"code":-6,"message":"Insufficient funds"},"id":"9476165379485093"}"

**Comment by hielscher92** [comment] 2020-12-05 19:06
It still doesn't work :(

**Comment by izzycsy** [comment] 2020-12-07 08:40
@UserMaxL @DanielHirsbrunner @hielscher92 , yes we're still trying to reproduce the issue. Thank you for your patience.

**Comment by UserMaxL** [comment] 2020-12-07 17:11
Looking at the answers from Ahmed (Senior Software Engineer) the issue is known and understood I think: "I need to quickly address something regarding this. When you use the dex you may receive "wrapped DFI" which is equivalent to regular dfi but you cannot send this with send to address. The app has to handle multiple operations to consolidate and transfer the two different types of dfi you hold." Hope for a fix soon.

**Comment by izzycsy** [comment] 2020-12-08 11:44
@UserMaxL @DanielHirsbrunner @hielscher92 @DanielHirsbrunner Hi all, please refer to the Telegram channel, a set of instructions has been posted there and it may be able to solve the issue you're facing. <https://t.me/defiblockchain/28689>

If not, please drop your telegram username here, and I'll drop you a DM for further discussion. Thank you for your patience on this matter. 

If your issue has been resolved, do state here as well. Thank you for your patience on this matter.

**Comment by UserMaxL** [comment] 2020-12-08 12:08
For step 2, please be aware that you need to use: "listaccounts {} true true true" to get your addresses only.

**Comment by muelln** [comment] 2020-12-08 14:20
Awesome it worked out. One hint coming from the telegram group. Use listaccounts {} false true true. "0" indicates the addresses you want to transfer to UTXO (DFI). Super

**Comment by DanielHirsbrunner** [comment] 2020-12-08 17:17
Looks good for me, Thanks alot

**Comment by ericfmiller** [comment] 2020-12-19 01:31
I am not a coder and I am not having any luck getting this solution to work. I must be misunderstanding the instructions. Can someone explain them in an even simpler way? I would really like to withdraw my DFI soon. Thanks in advance.

**Comment by ericfmiller** [comment] 2020-12-19 01:33
For example, do I list my DFI address inbetween {}? I need instructions that basic.

**Comment by ericfmiller** [comment] 2020-12-19 01:42
1. Check getbalance that it is less than the DFI
*When I type getbalance into the councle, I get the number "1.06636051" what is the purpose of this step?*

2. Now we need to convert the token DFI into UTXO DFI. Use listaccounts to list all addresses that are holding tokens. Look for those that are with @DFI. Not the amount field and the addresses. Say in this example the address is dXXXXXXXXXXXXXXXXX and the amount is 12.3@DFI.
*When I type list accounts, I get way to many addresses. I know there is a way to show only my address, but am not sure how to get this step to work." 

3. Check the total amount the address holds by doing getaccount dXXXXXXXXXXXXXXXXX.
*When I type in the address that I would send outside DFI into the DEX wallet with, I get an error "does not refer to any valid address."

4. Convert the token DFI of to UTXO by doing: accounttoutxos dXXXXXXXXXXXXXXXXX {"dXXXXXXXXXXXXXXXXX":"12.3@DFI"}. 
*I haven't gotten this far, as should be fairly obvious. Please, I really need help here.*

If you get the error Can't find any UTXO's for owner, do sendtoaddress dXXXXXXXXXXXXXXXXX 0.01 first, wait for confiramtion before trying the accounttoutxos command again.

5. Wait for confirmation, then check getbalance, you should see your UTXO DFI increases, now you should be able to send more DFI.

**Comment by KermitIsBack** [comment] 2020-12-19 08:42
@ericfmiller It looks like beginning next week the problem will be solved with an app update. I think this is the most secure way. Otherwise please send me the screen print of the "listaccounts {} true true true" command and i can send you a copy paste instruction

**Comment by DanielHirsbrunner** [comment] 2020-12-19 10:45
> For example, do I list my DFI address inbetween {}? I need instructions that basic.

Check out this nice instruction with printscreens if you don't wanna wait: https://defichain-wiki.com/wiki/How_to_%22rescue%22_stuck_DFI

**Comment by ericfmiller** [comment] 2020-12-19 12:29
I was able to figure it out using a reddit post. I'm all set. Thanks

**Comment by RikkeES** [comment] 2020-12-20 13:47
I also have this issue!

**Comment by ericfmiller** [comment] 2020-12-20 13:56
Here is what I used to solve it:
https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_df

They also stated on telegram that they will be updating the wallet in a few
days to solve the problem.

**Comment by izzycsy** [comment] 2020-12-29 06:55
@ericfmiller glad you manage to figure it out! Thanks for the help @DanielHirsbrunner 🙏🏼
@RikkeES did you manage to follow the tutorial on Reddit?

**Comment by RikkeES** [comment] 2020-12-29 10:28
Hi Eric,

Yes it worked like a charm, thanks a lot for your help.

Kind regards
Med venlig hilsen
Saludos coordiales



Rikke Hrab / Co. Founder

rikke@sativasana.com / 691364595
Sativasana

www.sativasana.com

**Comment by ericfmiller** [comment] 2020-12-29 13:37
Glad to hear that!

**Comment by izzycsy** [comment] 2020-12-29 19:25
Fantastic, I'll close this issue. Thank you all.

**Closed by izzycsy** 2020-12-29 19:25 UTC
Labels: duplicate, good first issue, pending
