### ISSUE TITLE
BerkeleyBatch: Error -30974, can't open database wallet.dat

### ISSUE THREAD

**Issue by Morhpois01** [DeFiCh/app#972] opened 2021-06-16 19:44 UTC
#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS):  Big Sur 11.3
– Current free storage capacity: 1 T
<img width="1440" alt="Bildschirmfoto 2021-06-16 um 18 39 44" src="https://user-images.githubusercontent.com/82651261/122282593-de786280-ceeb-11eb-9af3-33d5e929adac.png">

**Comment by izzycsy** [comment] 2021-06-17 11:12
Hi @Morhpois01 , can you try another `wallet.dat`? I'll provide the steps. You should be able to find other wallet.dat in the `wallets` folder, unless you've stored elsewhere on your PC. 

For Mac, the wallets folder is located here:
`Go to Folder` > `/Users/<username>/Library/Application Support/Defi/wallets/`

In the wallets folder you'll likely see wallet-bak-123456789 as well, these are additional backups.

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/122385936-eeea1500-cf9f-11eb-88c0-dcf1c3a364c4.png">

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/122271024-894f4780-cf11-11eb-9d6a-247e85c9b937.png">

1. In the app, `Exit Wallet` 
<img width="236" alt="Exit Wallet" src="https://user-images.githubusercontent.com/65014479/122268801-18a72b80-cf0f-11eb-9a2c-7a0f36595111.png">

2. `Restore Wallet via Backup`
Select another wallet.dat in the `wallets` folder or where you've specified your other backups. 

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/122268837-23fa5700-cf0f-11eb-9dd8-54f108ca8476.png">

**Comment by Morhpois01** [comment] 2021-06-17 13:12
Hello Bella,

Other .dat files works perfectly. I tried the wallet from my mom and it
works.

I got also many bak.xxxxxxx wallets/files but when I open them, they app
also ask me to create a new password and they are empty.

Once I open "my" wallet/.dat file. I can see the my defi wallet plus my
liquid mining pools, everything like it should. And it is locked. Once I
wanna unlock the wallet and enter my password, I get the mentioned error..

Little bit frustrating, since we are talking about over 60k usd.



Bella ***@***.***> schrieb am Do., 17. Juni 2021, 13:12:

**Comment by Morhpois01** [comment] 2021-06-17 13:25
Hi Bella,

U-Zyn asked me to open my wallet file and do an backup of it. Close everything and reopen it again.

I have done it as well and I get the same error once I wanna unlock my wallet..

**Comment by uzyn** [comment] 2021-06-17 13:35
Your wallet file is corrupted. Sorry, this is out of scope (not a bug) and we can’t help you there. Hope you have a backup or try to google and attempt to recover. 

https://www.google.com/search?q=berkeleybatch+error

https://bitcointalk.org/index.php?topic=703481.0

**Closed by uzyn** 2021-06-17 13:35 UTC
Labels: kind/bug, needs/triage, version/2.5.1
