### ISSUE TITLE
Version 2.9.3 crash at OSX 10.15.7

### ISSUE THREAD

**Issue by goofy79** [DeFiCh/app#1160] opened 2022-03-17 15:41 UTC
Hello, 

i want to Update from 2.9.1 to 2.9.2 - but it stops at the start screen. Than i try the 2.9.3 here i get an system Error 
(2.9.1 work without problems)

- DeFiCh/app Version:  2.9.3
- Operating System (OS):  OSX Catalina 10.15.7
– RAM (GB): 8GB
– CPU (Intel Core i5/i7/etc.): Intel i7
- Current free storage capacity: 30GB

```
Process:               DeFi Wallet [2424]
Path:                  /Applications/DeFi Wallet.app/Contents/MacOS/DeFi Wallet
Identifier:            DeFi Wallet
Version:               2.9.3 (2.9.3)
Code Type:             X86-64 (Native)
Parent Process:        DeFi Wallet [2419]
Responsible:           DeFi Wallet [2419]
User ID:               501

Date/Time:             2022-03-17 16:25:25.889 +0100
OS Version:            Mac OS X 10.15.7 (19H1824)
Report Version:        12
Anonymous UUID:        1DAFDB48-7E77-25DE-1BB0-734CCFB5642F


Time Awake Since Boot: 9300 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2424]

VM Regions Near 0x20:
--> 
    __TEXT                 0000000109cfa000-0000000109cfc000 [    8K] r-x/r-x SM=COW  /Applications/DeFi Wallet.app/Contents/MacOS/DeFi Wallet

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff6e809e41 nanov2_forked_calloc + 7
1   libsystem_malloc.dylib        	0x00007fff6e7f4f59 malloc_zone_calloc + 99
2   libsystem_malloc.dylib        	0x00007fff6e7f4ed9 calloc + 24
3   libobjc.A.dylib               	0x00007fff6d48dc40 allocateBuckets(unsigned int) + 29
4   libobjc.A.dylib               	0x00007fff6d48d6d2 cache_fill + 283
5   libobjc.A.dylib               	0x00007fff6d48d16d lookUpImpOrForward + 527
6   libobjc.A.dylib               	0x00007fff6d48c9d9 _objc_msgSend_uncached + 73
7   libxpc.dylib                  	0x00007fff6e89389e xpc_atfork_child + 125
8   libSystem.B.dylib             	0x00007fff6b58eab8 libSystem_atfork_child + 59
9   libsystem_c.dylib             	0x00007fff6e6988ad fork + 40
10  com.github.Electron.framework 	0x0000000109d181ef uv_spawn + 527
11  com.github.Electron.framework 	0x00000001104ad941 node::PromiseRejectCallback(v8::PromiseRejectMessage) + 234001
12  com.github.Electron.framework 	0x000000010ad581fb v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651
13  ???                           	0x0000001507f0aa38 0 + 90327525944
14  ???                           	0x0000001507e8c862 0 + 90327009378
15  ???                           	0x0000001507e8c862 0 + 90327009378
16  ???                           	0x0000001507e8c862 0 + 90327009378
17  ???                           	0x0000001507e8c862 0 + 90327009378
18  ???                           	0x0000001507e8c862 0 + 90327009378
19  ???                           	0x0000001507e8c862 0 + 90327009378
20  ???                           	0x0000001507f5ab62 0 + 90327853922
21  ???                           	0x0000001507e89dcf 0 + 90326998479
22  ???                           	0x0000001507fab9b6 0 + 90328185270
23  ???                           	0x0000001507e8c862 0 + 90327009378
24  ???                           	0x0000001507e8c862 0 + 90327009378
25  ???                           	0x0000001507e8c862 0 + 90327009378
26  ???                           	0x0000001507e8c862 0 + 90327009378
27  ???                           	0x0000001507e8c862 0 + 90327009378
28  ???                           	0x0000001507e8c862 0 + 90327009378
29  ???                           	0x0000001507f5ab62 0 + 90327853922
30  ???                           	0x0000001507e89dcf 0 + 90326998479
31  ???                           	0x0000001507fab9b6 0 + 90328185270
32  ???                           	0x0000001507e8c862 0 + 90327009378
33  ???                           	0x0000001507e8c862 0 + 90327009378
34  ???                           	0x00000015000b575f 0 + 90195056479
35  ???                           	0x0000001507e8c862 0 + 90327009378
36  ???                           	0x00000015000b575f 0 + 90195056479
37  ???                           	0x0000001507e8a89c 0 + 90327001244
38  ???                           	0x0000001507e8a5c7 0 + 90327000519
39  com.github.Electron.framework 	0x000000010ae281cc v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 684
40  com.github.Electron.framework 	0x000000010ad08ff9 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 713
41  com.github.Electron.framework 	0x00000001103498e8 node::CallbackScope::~CallbackScope() + 2184
42  com.github.Electron.framework 	0x0000000110349bd3 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 195
43  com.github.Electron.framework 	0x0000000109e6df7d v8::CodeEvent::GetScriptName() + 173229
44  com.github.Electron.framework 	0x0000000109dbf0cd v8::CodeEventHandler::~CodeEventHandler() + 338845
45  com.github.Electron.framework 	0x0000000109dabcbd v8::CodeEventHandler::~CodeEventHandler() + 259981
46  com.github.Electron.framework 	0x0000000109dab9fc v8::CodeEventHandler::~CodeEventHandler() + 259276
47  com.github.Electron.framework 	0x0000000109dec51f v8::internal::compiler::RawMachineAssembler::TargetParameter() + 6015
48  com.github.Electron.framework 	0x000000010c90578f node::AsyncResource::get_async_id() const + 6114815
49  com.github.Electron.framework 	0x000000010ce97945 operator delete[](void*) + 3026085
50  com.github.Electron.framework 	0x000000010ce9bb65 operator delete[](void*) + 3043013
51  com.github.Electron.framework 	0x000000010ce98ebd operator delete[](void*) + 3031581
52  com.github.Electron.framework 	0x000000010cea6a4f operator delete[](void*) + 3087791
53  com.github.Electron.framework 	0x000000010ce9bb65 operator delete[](void*) + 3043013
54  com.github.Electron.framework 	0x000000010ce94d75 operator delete[](void*) + 3014869
55  com.github.Electron.framework 	0x000000010ceb92bc operator delete[](void*) + 3163676
56  com.github.Electron.framework 	0x000000010cb4f23e node::AsyncResource::get_async_id() const + 8513710
57  com.github.Electron.framework 	0x000000010cb6cfdd node::AsyncResource::get_async_id() const + 8635981
58  com.github.Electron.framework 	0x000000010cbab805 node::AsyncResource::get_async_id() const + 8892021
59  com.github.Electron.framework 	0x000000010cbaa972 node::AsyncResource::get_async_id() const + 8888290
60  com.github.Electron.framework 	0x000000010cbaaf3f node::AsyncResource::get_async_id() const + 8889775
61  com.apple.CoreFoundation      	0x00007fff349021e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
62  com.apple.CoreFoundation      	0x00007fff34902183 __CFRunLoopDoSource0 + 103
63  com.apple.CoreFoundation      	0x00007fff34901f9d __CFRunLoopDoSources0 + 209
64  com.apple.CoreFoundation      	0x00007fff34900cb9 __CFRunLoopRun + 937
65  com.apple.CoreFoundation      	0x00007fff349002b3 CFRunLoopRunSpecific + 466
66  com.apple.HIToolbox           	0x00007fff3351baad RunCurrentEventLoopInMode + 292
67  com.apple.HIToolbox           	0x00007fff3351b7c5 ReceiveNextEventCommon + 584
68  com.apple.HIToolbox           	0x00007fff3351b569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
69  com.apple.AppKit              	0x00007fff31b64659 _DPSNextEvent + 883
70  com.apple.AppKit              	0x00007fff31b62ea0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
71  com.apple.AppKit              	0x00007fff31b54bae -[NSApplication run] + 658
72  com.github.Electron.framework 	0x000000010cbac116 node::AsyncResource::get_async_id() const + 8894342
73  com.github.Electron.framework 	0x000000010cbaa9e2 node::AsyncResource::get_async_id() const + 8888402
74  com.github.Electron.framework 	0x000000010cb6d96a node::AsyncResource::get_async_id() const + 8638426
75  com.github.Electron.framework 	0x000000010cb37871 node::AsyncResource::get_async_id() const + 8416993
76  com.github.Electron.framework 	0x000000010be3d424 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5186084
77  com.github.Electron.framework 	0x000000010be3ed62 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5192546
78  com.github.Electron.framework 	0x000000010be3ab30 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5175600
79  com.github.Electron.framework 	0x0000000109ff0255 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 1957
80  com.github.Electron.framework 	0x0000000109ff1423 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 6515
81  com.github.Electron.framework 	0x0000000109ff0ea1 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 5105
82  com.github.Electron.framework 	0x0000000109fef45d v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12189
83  com.github.Electron.framework 	0x0000000109fefd93 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 739
84  com.github.Electron.framework 	0x0000000109d22be8 ElectronMain + 152
85  libdyld.dylib                 	0x00007fff6e638cc9 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff6e809e3a  rbx: 0x0000000000000004  rcx: 0x00007fff6d4ab3f0  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000040  rbp: 0x00007ffee5f00060  rsp: 0x00007ffee5f00038
   r8: 0x0000000000000003   r9: 0x00007ffee5f000d8  r10: 0x0000000100000000  r11: 0x00007ffee5f000d0
  r12: 0x00007fff95040000  r13: 0x00007fff9504d6e8  r14: 0x0000000000000001  r15: 0x0000000000000040
  rip: 0x00007fff6e809e41  rfl: 0x0000000000010246  cr2: 0x0000000000000020
  
Logical CPU:     4
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14
```

**Comment by thedoublejay** [comment] 2022-03-29 07:51
Hi @goofy79 can you generate app logs?

**Comment by goofy79** [comment] 2022-03-29 08:04
No problem, can you tell me how to clean the actual Log.
the you have a clear Log for Debug.

**Comment by thedoublejay** [comment] 2022-03-29 08:07
@goofy79 When you open the app, on the menu bar there's an option of Logs. You can generate app or debug logs. You can attach them here. Thank you!

**Comment by goofy79** [comment] 2022-03-29 08:09
I know - but in this log, there are all logs from the first Version in installed.
Is it possible to clean the actual Log than i can start with a empty Log

**Comment by thedoublejay** [comment] 2022-03-29 08:14
@goofy79 Hmm, might need to delete the logs based on your folder. It's ok I just need to read the latest logs

**Comment by goofy79** [comment] 2022-03-29 08:19
I've send you the Log File per eMail - it's OK ?

**Comment by goofy79** [comment] 2022-03-30 07:50
> Sure @goofy79 [engineering@defichain.com](mailto:engineering@defichain.com)

Did you received my logs ? Or do you need the Node Logs too ?

**Comment by thedoublejay** [comment] 2022-03-30 08:36
Hi @goofy79 we haven't received it. Can you double check? engineering@defichain.com

**Comment by izzycsy** [comment] 2022-03-30 10:35
Hi @Mark76DefiChain , thanks for your reply in #1163 , app logs well received.

**Comment by neuriGH** [comment] 2022-03-30 20:57
Same here, as i described in [#1163](https://github.com/DeFiCh/app/issues/1163)

**Comment by thedoublejay** [comment] 2022-03-31 05:41
HI @goofy79 @neuriGH, this is a preview build of the upcoming app release (with the new node). Can you try if this version is opening on your end? - https://github.com/DeFiCh/app/releases/tag/v2.10.0-alpha.1

Take note it's a dev build so only run it but don't do any transactions yet

**Comment by goofy79** [comment] 2022-03-31 06:19
Hi, yes, it work well. It starts without problems and the version beginn to sync.
Looks very good. Where was the Problem ?

**Comment by Mark76DefiChain** [comment] 2022-03-31 07:21
v2.10.0-alpha.1 started without problems and finished blockchain sync - looks good

**Comment by thedoublejay** [comment] 2022-03-31 08:38
@goofy79 @Mark76DefiChain It's hard to pinpoint now as per checking the app logs, there are no app related issues. It might be a problematic node but will need more logs to find out the root cause

**Comment by goofy79** [comment] 2022-04-02 09:14
Version 2.10.0-rc.1 work well too 👍

**Comment by thedoublejay** [comment] 2022-04-03 22:41
Will close this. Fixed with https://github.com/DeFiCh/app/releases/tag/v2.10.0

**Closed by thedoublejay** 2022-04-03 22:41 UTC
Labels: kind/bug, needs/triage
