### ISSUE TITLE
I want to add Ukraine language to the desktop wallet

### ISSUE THREAD

**Issue by dzensik** [DeFiCh/app#1195] opened 2022-04-30 11:05 UTC
Hi guys, I would like to add by myself the Ukraine language. How should I proceed? Just open a PR? Is there anybody who should make the decision first whether it is something valueble and therefor is worth to add it? Thank you in advance

**Comment by izzycsy** [comment] 2022-05-05 09:16
Hi @dzensik , feel free to contribute a PR. Posting your suggestion here might have more responses from the community https://www.reddit.com/r/defiblockchain/new/. Closing this issue as it's not a bug. Thank you.

**Closed by izzycsy** 2022-05-05 09:16 UTC
Labels: kind/feature, needs/triage
