### ISSUE TITLE
Wallets are not displayed

### ISSUE THREAD

**Issue by rang3r72** [DeFiCh/app#150] opened 2020-12-20 07:34 UTC
Hi, I have the problem that my wallets are no longer displayed, although the nodes are synchronized. In Liquidity and DEX everything works normally. I also get my rewards. But how do I get the walltes displayed again?

Thank you in advance.

![grafik](https://user-images.githubusercontent.com/76251952/102707704-91e5fe80-429d-11eb-83f8-a72557aaedea.png)

**Comment by UserMaxL** [comment] 2020-12-20 18:56
I had the same, I re entered the seed and it works fine since then.

**Comment by izzycsy** [comment] 2020-12-21 10:01
Hi @rang3r72 , thanks for your feedback. We're trying to investigate this issue, thank you for your understanding.

**Comment by izzycsy** [comment] 2020-12-24 08:46
Hi @rang3r72 , did you try re-entering your mnemonic seed to restore wallet? If it's still didn't work, please send your app & binary logs. Thank you.  
<img width="339" alt="App log" src="https://user-images.githubusercontent.com/65014479/103075923-90069d00-4607-11eb-93aa-995511f76b19.png">

**Comment by izzycsy** [comment] 2020-12-24 11:22
Hi @rang3r72 , may I know if the issue is resolved with the new update v2.1.4?
https://github.com/DeFiCh/app/releases/tag/v2.1.4

**Comment by rang3r72** [comment] 2020-12-26 06:22
Hello,
after I re-entered the seed everything worked.

**Comment by rang3r72** [comment] 2020-12-26 06:23
n der Version 2.1.4 hat es auch funktioniert.

**Comment by izzycsy** [comment] 2020-12-26 10:16
@rang3r72 Good to hear! I'll close this issue then.

**Closed by izzycsy** 2020-12-26 10:16 UTC
Labels: duplicate
