### ISSUE TITLE
Cannot send ETH token: Got error in handleFallbackSendToken: Insufficient token in account

### ISSUE THREAD

**Issue by flotzke** [DeFiCh/app#722] opened 2021-04-03 14:51 UTC
Please correct the very basic functionality in your app,
which is sending and receiving first before dreaming of any other things!!!

Did you ever TEST your app on Windows yourself?
It is absolutely un-usable!

Neither sending of DFI nor any token is working correctly.

With this behaviour it seems very unprofessional!
And i will not rely on it in the future.

I got the following error all the time:
Got error in handleFallbackSendToken: Insufficient token in account
When sending ETH token...
When sending DFI still the UTXO error from 3 months ago appears.
PLEASE FIX THESE BASIC OPERATIONS ASAP!

**Comment by izzycsy** [comment] 2021-04-04 12:29
Hi @flotzke , thanks for your feedback, it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; `utxoDFI` and `accountDFI`. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via be DeFi Wallet app. 

  Firsty, check via CLI: 
 `getbalance` — utxoDFI
`gettokenbalances` — accountDFI 

From your output 
```
gettokenbalances
[
  "3.123456768@0", — accountDFI
  "XXXXXXXXXX@2",
  "XXXXXXXXXX@5"
]
```

Can you try to send 1 DFI to yourself:
1. copy your address (the one that you're planning to use to add liquidity)
2. send DFI
3. 1 DFI
4. Paste the address 
5. Try the function again

By sending to yourself, you're converting your accountDFI to utxoDFI. utxoDFI is used for transaction fees.

**Comment by flotzke** [comment] 2021-04-04 16:00
Why is the app still not able to do that ???
I am a user and not an IT-specialist?

Why do i need to know such things and do workarounds all the time?

Just fix it please !

BTW:

When i try to execute your send 1 DFI to myself TIP, i get:

'Nicht genügend UTXO DFI für die Transaktionsgebühren vorhanden. Bitte schicke ein paar DFI von einer Exchange oder einem anderen Wallet zu dieser Adresse und versuche es erneut.'

This is a very old problem, please fix it.

I am using a mac now, same error !

**Comment by izzycsy** [comment] 2021-04-05 10:57
Hi @flotzke , the team is working on improving the UX. This is not a bug it's just how the app works. Your transaction fees are paid in utxo DFI (coin form) and the rewards you receive are in account DFI (token form). The old issue was your needed to convert the tokens manually via the CLI, this improvement where you send to yourself is basically converting your DFI to coin form so you can continue using the functions or send them out. 

May I know what's your `getbalance`? Do you have several addresses? It could be that your utxoDFI are on various addresses. Thank you for your patience.

**Comment by flotzke** [comment] 2021-04-05 19:32
The app is full of errors and is not usable.
It needs a restart after each action.
Old errors are still in it, instead you add BCH and DOGE to the app...
No one needs these...please fix your errors first!

And you claim these are not bugs but features?

If i try adding liquidity to the DFI-BTC Pool i get the error:

'Bitte warte bis deine Transaktion dem nächsten Block hinzugefügt wurde, bevor du mit einer neuen Transaktion fortfährst.'
Is this a feature too ???

**Comment by flotzke** [comment] 2021-04-05 20:01
When i start the app it shows 'synchronized' even if it is NOT synchronized.
This has been reported as well several times and is still not fixed.

**Comment by uzyn** [comment] 2021-04-06 11:36
Blockchain is decentralized, your app doesn't know the latest block height. Leave it on for awhile longer and you'll know. 

You are probably spoiled with metamask-like experience. Firstly NativeDeFi blockchain is not straight-forward and I think we're progressing well. Things will get a lot more smoother soon, but at the same time we also need to move in a fast pace to bring all the new features live.

Also, we are moving to Light Wallet model. Team's also working hard on that. You can follow the progress at https://github.com/defich/jellyfish and https://github.com/DeFiCh/fiber

Closing this ticket as it is not an issue but comments. Thanks for your feedback.

**Closed by uzyn** 2021-04-06 11:36 UTC
Labels: needs/kind, needs/triage
