### ISSUE TITLE
Wallet Backup - no backup-file generated

### ISSUE THREAD

**Issue by MRHMuc** [DeFiCh/app#461] opened 2021-02-02 11:57 UTC
Dear DeFiCh-Team,

I am opening this issue as recommended 
  in  'r/defiblockchain' 
  by TECH TEAM 
  for topic "Wallet Backup" 
  user 'u/MarkMuc' 
with attached log files.

### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details
- **Current DeFi App Version:  2.1.15
- **Previous DeFi App Version: n/a
- **Operating System (OS): macOS 10.15.7

### Screenshot(s) / screen recording(s) of issue
n/a

### Actual Behavior
APP installed some days ago and Backup was working fine.
Yesterday I have encrypted wallet manually using 'encryptwallet <PASSPHRASE>'.
When done with adding Liquidity I wanted to make a new BACKUP-file via MENU - WALLET - BACKUP WALLET.
Pop-up Window allowed to enter BACKUP-file-name and SAVE-button to be executed.
Unfortunately there is no BACKUP-file created in selected folder.

### Expected Behavior
Expect to get an encrypted BACKUP-file generated.

### App log / binary log / app config
File: 'app logs.zip' is attached.
[app logs.zip](https://github.com/DeFiCh/app/files/5910879/app.logs.zip)

Please let me know if you need further information.

Thank you for your support.

Best, Mark

**Comment by izzycsy** [comment] 2021-02-02 12:08
Hi @MRHMuc , thanks for your feedback, logs well received. Please give the team time to investigate the issue. Thank you. 

Hi @teich1961 , I'll keep you updated here as well. Thank you.

**Comment by MRHMuc** [comment] 2021-02-02 12:21
Hi @izzycsy ,
I have just tested the following and sharing for your information:
1. unlock the wallet with 'walletpassphrase PASSPHRASE 60'
2. check if wallet is unlocked with 'getwalletinfo'
3. initiate BACKUP while wallet is unlocked
--> This generates an unencrypted backup-file.
Thank you.

**Comment by teich1961** [comment] 2021-02-02 12:26
thank you very much, was successful. Now I can sleep peacefully again. Thank you

**Comment by MRHMuc** [comment] 2021-02-02 12:35
Hi @teich1961, 
In case you responded to my test unlocking the wallet to generate a backup file that this will only create an unencrypted backup-file in TXT format. So keep it in a secure space only.
I hope the team will come up with a bugfix to get encrypted backup files.
Best, Mark

**Comment by tame81** [comment] 2021-02-02 16:16
Hi,

I have the same issue: no encrypted wallet backup will be made. Please fix this!

**Comment by izzycsy** [comment] 2021-02-04 09:54
Hi @tame81 , thanks for your feedback. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

**Comment by MRHMuc** [comment] 2021-02-04 14:27
Hi @izzycsy, 
Sorry for bothering again.
Today my walled does not open. When I open it is stuck at 'the first screen' (see attached screenshot). 

Would you recommend me to install the wallet new? If so, do you know a link where re-install process for iOS is described - so I am on the safe side? 
Thank you.

![Screenshot 2021-02-04 at 15 23 34](https://user-images.githubusercontent.com/78418304/106906380-660fc280-66fd-11eb-92d4-c38716aa9e82.png)

**Comment by OtenMoten** [comment] 2021-02-07 13:10
Same here. I de- and encrypt my wallet like this https://github.com/DeFiCh/app/wiki/Wallet-Encryption 

Currently I save the encrypted `wallet.dat` file to backup the wallet. I also have the seed but there is another error that happens non-reproduciable that some address that where generated in the wallet are marked with a **red error note: "This address is not included in seed."**

And I also can't backup via the App's GUI because no file is generated.

App Version here is `2.1.16`

Greetz

**Comment by OtenMoten** [comment] 2021-02-10 04:47
> Same here. I de- and encrypt my wallet like this https://github.com/DeFiCh/app/wiki/Wallet-Encryption
> 
> Currently I save the encrypted `wallet.dat` file to backup the wallet. I also have the seed but there is another error that happens non-reproduciable that some address that where generated in the wallet are marked with a **red error note: "This address is not included in seed."**
> 
> And I also can't backup via the App's GUI because no file is generated.
> 
> App Version here is `2.1.16`
> 
> Greetz

Works for me now. I use Ubuntu 20.04

**Comment by MRHMuc** [comment] 2021-02-16 16:05
Hi @izzycsy  
Just wanted to update you.
Backup-files are created fine for me after updating to v2.1.17.
Thank you.
Best, Markus

**Comment by izzycsy** [comment] 2021-02-22 09:19
Hi @MRHMuc , thanks for your update. This issue is resolved in the upcoming version of the app _ still undergoing testing. I'll be closing this issue in the mean time, should you face the same issue, please leave a comment with new information (include screenshots) and app logs. Thank you.

**Closed by izzycsy** 2021-02-22 09:19 UTC
Labels: bug

**Comment by Folderguion** [comment] 2021-02-24 11:07
Hello! Tnx for your help.

I'm on the version: 2.1.17 .
I just click on Wallet menu > Backup wallet > the folders explorer open up but there's no file to save. The only option is to press on Cancel on the explorer window.

The same happen when I go to Logs > any menu the same, no files generated.

I've gone through the post you linked but I don't understand the very first step of your instructions :" unlock the wallet with 'walletpassphrase PASSPHRASE 60' " > How to do this?

Thanks

**Comment by OtenMoten** [comment] 2021-02-25 13:30
> Hello! Tnx for your help.
> 
> I'm on the version: 2.1.17 .
> I just click on Wallet menu > Backup wallet > the folders explorer open up but there's no file to save. The only option is to press on Cancel on the explorer window.
> 
> The same happen when I go to Logs > any menu the same, no files generated.
> 
> I've gone through the post you linked but I don't understand the very first step of your instructions :" unlock the wallet with 'walletpassphrase PASSPHRASE 60' " > How to do this?
> 
> Thanks

You don't need to unlock if you haven't locked.
