### ISSUE TITLE
Insufficient UTXOS to perform swap

### ISSUE THREAD

**Issue by rang3r72** [DeFiCh/app#174] opened 2020-12-26 07:14 UTC
Hi,
I have some issues with the APP.

1.
I wanted to deposit money in liquidity pool, the order was not executed and since then I get the message "Insufficient UTXOS to perform swap".
This message appears now in DEX and Liquidity mining, and neither can be executed.

2.
Also, I can't send DFI's or BTC from the APP to the Cake wallets.

I am using version 2.1.4 on Windows.

**Comment by rang3r72** [comment] 2020-12-26 09:09
After I transferred DFIs to my APP, DEX and Liquidity Mining is going again.
**But the transfer from the APP to the Cake Wallet still does not work.**

**Comment by izzycsy** [comment] 2020-12-26 09:16
Hi @rang3r72 , thanks for your feedback. Did you try click on DeFi Blockchain generated address? 
<img width="375" alt="Click on DeFiChain" src="https://user-images.githubusercontent.com/65014479/103148750-f58c9200-479d-11eb-9d17-312fd29698ca.png">



If error still persist, could you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103148648-f670f400-479c-11eb-89fe-74d4185b2230.png">
<img width="511" alt="2 Komprimiere" src="https://user-images.githubusercontent.com/65014479/103148761-12c16080-479e-11eb-813e-4ff04cbf4757.png">

**Comment by rang3r72** [comment] 2020-12-26 10:00
Yes, I generated an address on Cake and it did not work. I tried the same thing on Bittrex, it doesn't work there either. I have sent the log files by email.
Thanks for your help,

**Comment by izzycsy** [comment] 2020-12-28 11:12
Hi @rang3r72 , currently coins can only be send to Defi app via Cake. We understand the trouble and the team is working on a solution. Thank you for the logs, will notify the team to look out for the email.

**Comment by jonho79** [comment] 2020-12-29 02:47
I'm having the same issue transferring out BTC, ETH and USDT to cake.

The error message is "Not enough balance on wallet accounts, call utxostoaccount to increase it." but I have the amount in Bitcoin as well as in DFI coin to pay any fees.

**Comment by izzycsy** [comment] 2020-12-29 08:46
@jonho79 , thanks for your feedback. Could you attach screenshots / screen recordings? Also, could you send your app logs please? We need more details in order investigate how to reproduce this issue. 

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103271516-6d082e80-49f5-11eb-902b-b3fa79b74609.png">

**Comment by jonho79** [comment] 2020-12-29 13:46
Hi Bella,

Thanks for your quick response.  The problem is that I requested a transfer
of bitcoin of 0.002 and I have 0.007 but it's saying I don't have enough
of  a balance.    Here's the screenshot of the error I'm getting.  I've
also attached the app logs.   Thanks.

[image: image.png]

**Comment by izzycsy** [comment] 2020-12-29 19:15
Hi @jonho79 , your links seems broken, please re-send them, thank you. 
This is what I see: 
<img width="454" alt="Screenshot 2020-12-30 at 3 14 51 AM" src="https://user-images.githubusercontent.com/65014479/103308341-36f69900-4a4d-11eb-9801-7be60dbde06a.png">

**Comment by jonho79** [comment] 2020-12-29 19:17
Ok, will do.

Regards,

Jon

**Comment by jonho79** [comment] 2020-12-29 19:52
Here's the zipped file with the 3 log files.  Let me know if it works this
time.  Thanks for the help.

**Comment by nordi6000** [comment] 2020-12-29 20:27
I have same error. Can not Sent DFI to Cake. Can not Swap on DEX and can not add liquidity to the pool.

![image](https://user-images.githubusercontent.com/49670309/103312085-4d383100-4a1c-11eb-9880-abe8b5b59925.png)
![image](https://user-images.githubusercontent.com/49670309/103312164-7b1d7580-4a1c-11eb-9aeb-183f7bccf0c5.png)
![image](https://user-images.githubusercontent.com/49670309/103312188-8cff1880-4a1c-11eb-8011-d6a3f9c30a6e.png)
[Error_29.12.2020.zip](https://github.com/DeFiCh/app/files/5752078/Error_29.12.2020.zip)

**Comment by izzycsy** [comment] 2020-12-30 11:02
Hi @jonho79 , all right. I've informed the team to look out for your email. Alternatively, you can drag and drop it here so I can escalate this. Thank you.

**Comment by izzycsy** [comment] 2020-12-30 11:04
Hi @nordi6000 , well received. Thank you for the screenshots. Please give us time to investigate this issue.

**Comment by izzycsy** [comment] 2020-12-31 06:47
Hi @rang3r72 @nordi6000 @jonho79 , the team is still investigating this issue. In the mean time, there’s a temporary solution to this, it could be that you've too little DFI UTXOs balance — which is required to perform swap and other functions. You could try convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>.

**Comment by jonho79** [comment] 2020-12-31 06:54
Hi Bella, I tried that already but it didn’t work. How many DFI coins would you need?  I had 16 the other day and the transfer still didn’t work.

Regards,

Jon

**Comment by izzycsy** [comment] 2020-12-31 07:05
@jonho79 , minimum DFI UTXOs required: `0.05`. I understand, please give us time to investigate this issue. Thank you for your patience.

**Comment by nordi6000** [comment] 2020-12-31 10:28
Hi Bella, I try this and it works. I must swap all my Address >>accounttoutxos address_from_above {"adress_from_above":"DFI_amount_to_convert@DFI"}<< withe this string and than I can Send it to Cake.
![image](https://user-images.githubusercontent.com/49670309/103406510-3a784600-4b5b-11eb-89e9-5c777bd839d9.png)

**Comment by nordi6000** [comment] 2021-01-09 12:49
Hello @jonho79 , I have install wallet 2.1.6 but my problem with the DFI-token to DFI-coin swap is still the same. 
I must still work with the workaround. But this is working perfect, is a little to do when I swap 7 addresses but then I can send my DFI. 
![image](https://user-images.githubusercontent.com/49670309/104091317-ee28b680-527c-11eb-86f3-9cc070c5d130.png)
The BinaryLog file is to big... up tu 159MB 

[Error_2.1.6.zip](https://github.com/DeFiCh/app/files/5791114/Error_2.1.6.zip)

**Comment by izzycsy** [comment] 2021-01-13 07:46
Hi @rang3r72, @jonho79, @nordi6001 , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.  

Regarding the issue `Unable to send BTC / ETH / USDT`, I'll link you to <https://github.com/DeFiCh/app/issues/195> which we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Closed by izzycsy** 2021-01-13 07:46 UTC
Labels: duplicate, fixing, need logs
