### ISSUE TITLE
DEX Swapping:not allowing to input any value from "from" to "to" side on dex

### ISSUE THREAD

**Issue by Cryptopat100** [DeFiCh/app#331] opened 2021-01-18 22:27 UTC
### Preflight Checklist

- [ ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:** V2.2.1.10
  
- **Previous DeFi App Version:** V1.2.1.7
  
- **Operating System (OS):** 10.15.5
  

### Screenshot(s) / screen recording(s) of issue 

`

`
### Actual Behavior

```
1. Open the app
2. Go to DEX
3. Click on FROM
4. SELECT DFI
5. CLICK ON TO
6. SELECT BTC
7. CLICK ON RECIEVE ADD.
8. SELECT WALLET CONTAINING DFI
9. INPUT AMOUNT ON EITHER SIDE PRODUCES (SOMETHING WENT WRONG) ERROR
```
-->

### App log / binary log / app config
Archive.zip
<img width="1440" alt="Screen Shot 2021-01-18 at 5 17 15 PM" src="https://user-images.githubusercontent.com/77644952/104967863-68121b80-59b2-11eb-9f7b-be98d9db92f4.png">

[Archive.zip](https://github.com/DeFiCh/app/files/5832623/Archive.zip)

**Comment by MrStryker** [comment] 2021-01-18 22:40
Duplicate of #280

**Comment by izzycsy** [comment] 2021-01-20 13:54
Hi @MrStryker , thanks for the help! 

Hi @Cryptopat100 , thanks for your feedback, regarding the issue `	DEX: Something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem. We would like to keep same issues in one thread. Logs well received. Thank you.

**Closed by izzycsy** 2021-01-20 13:54 UTC
Labels: duplicate
