### ISSUE TITLE
DeFi App deletes Wallet.dat BackUp

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#641] opened 2021-03-11 20:42 UTC
I am describing here a situation that has been reported to us by many users. 

When creating the wallet, the user is prompted to save a backup. This opens the following window under Windows.
![photo_2021-03-11_21-09-18](https://user-images.githubusercontent.com/65536965/110851593-8b21c300-82b1-11eb-8d66-4a074154d783.jpg)

Many users have reported that this backup file was deleted during the installation of an update. Apparently, this folder, which is suggested by default, is a very bad place to store a backup. 

So far, not many people have really lost money because most users with this problem were in possession of the 24 words. 

In the last few days, new users have entered the system who no longer have 24 words. If these users save the backup to the suggested location and then install an update, the whole fortune is lost. 

I recommend to use a better folder than default folder for saving. For example my files.

**Comment by cryptoexplained3** [comment] 2021-03-12 00:22
Damn, feel like this happened to me.

Joined not too long ago so wasn't able to create a 24 word key. Now I've just updated to the latest v2.3.0. and I'm unable to find my DAT file. 

Is there any way to recover this? Or have I just lost everything? Guess I made a mistake of not creating more backups.

**Comment by thedoublejay** [comment] 2021-03-12 01:56
@cryptoexplained3 are you experiencing it v2.3.0? Some users are reporting it with v.2.3.1

**Comment by thedoublejay** [comment] 2021-03-12 02:05
@RobinTorque this folder is the location of installation files. I'm not sure why it's presented as default path for some users.

**Comment by cryptoexplained3** [comment] 2021-03-12 02:29
> @cryptoexplained3 are you experiencing it v2.3.0? Some users are reporting it with v.2.3.1

Apologies, meant to say this occurred with the v2.3.1 update. (v2.3.0 -> v2.3.1)

**Comment by cryptoexplained3** [comment] 2021-03-12 04:27
Initially I was having trouble getting past the "Unable to start blockchain" page. But then I was able to get into the app after opening up the defi .conf file and removing the wallet properties.

However, I don't think I was using the correct .dat file (which I think I was able to recover). After trying to adjust to what I think is the correct .dat file, now I'm back to the "Unable to start blockchain" page and cannot get around it with the .conf file.

Just added my app log file, any help or ideas here would be greatly appreciated.

[applog_2021_03_11.log](https://github.com/DeFiCh/app/files/6127595/applog_2021_03_11.log)

**Comment by thedoublejay** [comment] 2021-03-12 04:50
@cryptoexplained3  thank you for this. We're currently working on a fix for this.

**Comment by tommuhm** [comment] 2021-03-12 08:46
I think this is one of the most important issues atm. Maybe it would also make sense to disable the updates from 2.3.0 to 2.3.1 till this issue is fixed?

**Comment by thedoublejay** [comment] 2021-03-12 08:49
@tommuhm Yes we have disabled the v2.3.1 while checking on this issue.

**Comment by johnny72764** [comment] 2021-03-14 22:20
Help! My wallet never actually synched to the website and was lost? during an upgrade. I currently am running 2.3.0 and have both my catchphrase and seed phrases; however, when trying to restore my wallet through the app. it asks for me to enter my catchphrase first before the 24 seed phrases, yet, there is no entry field to enter catchphrase? What to do? I don't want to lose and or stop investing.

**Comment by RobinTorque** [comment] 2021-03-15 08:29
@johnny72764 https://defichain-wiki.com/wiki/Suggestion_for_using_the_DeFi_app

**Comment by izzycsy** [comment] 2021-03-16 12:22
Hi @johnny72764 , thanks for your feedback, the team has halted v2.3.1 at the moment due to some issues — which you might be facing on v2.3.0. If you keep your passphrase & wallet.dat safe, there shouldn't be an issue.  I'll update you again when the team fixes it and is ready for release. In the mean time please refer to the official channels for updates. 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)
[DeFiChain Announcements (EN)](https://t.me/defichain_announcements)

You can make a copy of your wallet.dat for safe keeping, routes as stated: 
Windows — C:  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder:  /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat

**Comment by BigE1269** [comment] 2021-03-18 19:49
I am experiencing the same problem. I am a new user and did not record my passphrase and I updated the app. When i re-opened my wallet was gone and when asked to recover them through the app it the files no longer existed. Is there anyway it can be reocvered? Any assistance greatly appreciated.

**Comment by izzycsy** [comment] 2021-03-19 06:50
Hi @BigE1269 , the team is fixing this. Yes so long as you keep your passphrase & wallet.dat safe. Please refer to the above comment. Thank you for your understanding.

**Comment by BigE1269** [comment] 2021-03-19 06:57
Thanks for your response. The issue is I do not have my passphrase. Only been doing this for about a week and didn't write it down yet. And my wallet.dat is telling me my wallet is at $0. Does this mean I lost my investment? What files do I need to send to you or a tech that would be capable of recovering it for me if it is still recoverable?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by izzycsy** [comment] 2021-03-19 08:56
Hi @BigE1269 , the passphrase (to be set by yourself) would be the first screen you encounter when you updated to / install v2.3.0, it's as important as your mnemonic seed. If you skipped setting a passphrase then you can rely on your `wallet.dat` and the wallet should not be locked. If you're about a week-old user, then you won't have mnemonic seed, but passphrase instead.

In v2.3.0, mnemonic seed does not exist for new users until the team can find a better way to utilise it. Hence the `passphrase` & `wallet.dat` are the ones you need to keep safe. Though if you're an existing user from before v2.3.0, you can still use your mnemonic seed to restore your wallet, but from v2.3.0 I would advice that you create a passphrase and write it down somewhere for safe keeping. 

We won't be able to recover your wallet for you as it's your own responsibility and on your own local PC, but we can guide you. If you did not delete any files you're unfamiliar with, your investments should be safe and stored in the `wallet.dat` file + passphrase.

You can make a copy of your wallet.dat for safe keeping, routes as stated:
Mac — Go to Folder: ` /Users//Library/Application Support/DeFi/wallets/wallet.dat`

Windows — C: ` \Users<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Try to Restore from wallet backup (wallet.dat).
<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/111755135-bc167f00-88d3-11eb-9a64-451a3d1dde7c.png">

**Comment by izzycsy** [comment] 2021-03-22 18:45
Hi @johnny72764 @cryptoexplained3 @tommuhm @BigE1269 	, update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by BigE1269** [comment] 2021-03-24 04:51
Hi Bella,

Thanks again for the reply. I misspoke when I said I did not know the passphrase. I do know that. What I do not know is the mnemonic seed. When I tried to reload/restore my previously saved wallets after updating the application; they said file not found/no longer exists because I saved it in the default folder the app directed me to save to. Could you please direct me in how to recover from wallet.dat when it tells me all previous restores fail? Thank you.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by izzycsy** [comment] 2021-03-26 12:32
Hi @BigE1269 , in v2.3.2 all new users would not have a mnemonic seed, the team has temporary stopped this feature until further notice. You should Restore Wallet from Backup (wallet.dat).  

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112629226-fb624400-8e6e-11eb-8ad7-02e066da39be.png">

You can make a copy of your wallet.dat and store it on a thumbdrive / external hard-disk. To find your wallet.dat route:
**Windows — C:**
Blockchain folder
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

**Mac — Go to Folder:**
`Blockchain folder /Users/<username>/Library/Application Support/Defi/wallets/wallet.dat`

**Comment by BigE1269** [comment] 2021-03-31 03:54
Bella,

Thank you again for your reply. I have followed your directions exactly and my wallet with my investment still does not appear. When I did the Defi App update on 3.11.21 it completely re-wrote my wallet.dat file. I enter my passphrase as instructed and it opens up the wallet but with a zero balance.  I have my actual address that I used to track my income on defichain-income.com and my log files. Is there a way to recover that way? Possibly backtrace my defichain-income address and then tie it to my actual passphrase to unlock and prove that it is in fact my account? Please let me know. Would hate to lose my investment due to a flaw in the app design. Appreciate any support. Thank you.

Sincerely,
Eric

**Comment by izzycsy** [comment] 2021-04-07 12:28
Hi @johnny72764 @cryptoexplained3 @tommuhm @BigE1269 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.

**Closed by izzycsy** 2021-04-07 12:28 UTC
Labels: kind/bug, triage/accepted

**Comment by cryptoexplained3** [comment] 2021-11-02 22:07
I was actually never able to get access to my account following the update. I have multiple .dat files saved (believe I was able to recover the ones that were deleted with the update).

I downloaded the newest version (2.6.5) but it's saying "Node is disconnected". Does the .dat file need to be in a specific file or go through a specific route? Or should I assume that if it says "Node is disconnected" then the dat file is corrupted?

Or maybe I shouldn't be using this version and I can try using an older version? Thanks
