### ISSUE TITLE
Network ERROR at new wallet 2.3.4

### ISSUE THREAD

**Issue by supervolot** [DeFiCh/app#849] opened 2021-05-12 07:17 UTC
#### What are your environment parameters?

- DeFi Wallet Version: 2.3.4
- Operating System (OS): WIN10
– Current free storage capacity: 80GB

#### Anything else we need to know? Many Errors at spv and a huge 240mb log file !!!
[debug.log](https://github.com/DeFiCh/app/files/6464162/debug.log)
[main.log](https://github.com/DeFiCh/app/files/6464164/main.log)

**Comment by izzycsy** [comment] 2021-05-12 08:39
Hi @supervolot , thanks for your feedback. Network error could be due to your location, the peers nearby for the app to sync — you're running the node (wallet) by yourself after all. Personally, I sometimes face a disconnected node to to my internet spike dropping, and although I can still use other applications like Chrome, Spotify etc, the DeFi Wallet is affected. Please give us time to investigate. Thank you.

**Comment by supervolot** [comment] 2021-05-12 10:24
> Hi @supervolot , thanks for your feedback. Network error could be due to your location, the peers nearby for the app to sync — you're running the node (wallet) by yourself after all. Personally, I sometimes face a disconnected node to to my internet spike dropping, and although I can still use other applications like Chrome, Spotify etc, the DeFi Wallet is affected. Please give us time to investigate. Thank you.

Hi, my internet is fine, so it looks like a bug on the new 2.3.4 wallet (ver. 2.3.3 was working fine)

**Comment by m4rk88** [comment] 2021-05-12 18:55
Hi,
got the same problem/behavior with 2.3.4 (2.3.3 Works without any issues)
Run on Win Server 2019 with plenty of free storage and memory capacity in a datacenter (1 gbits up and down).

**Comment by memzila** [comment] 2021-05-12 19:05
I have the same behavior. After some time when the wallet has run error messages about network errors. Old version has worked normally and i could keep running the wallet all the time.

**Comment by Faucet1313** [comment] 2021-05-13 11:05
Same issue for me with Windows server 2016 and defichain 2.3.3 and 2.3.4. Found some events that match the time of the network error. And what about you guys ?

**Comment by memzila** [comment] 2021-05-14 03:49
Issue still exist in 2.3.5. It even looks like the wallet app kills the whole connection from the pc to the internet. I have installed yesterday 2.3.5 and now i can't connect to the pc anymore from external

**Comment by supervolot** [comment] 2021-05-14 12:35
Still the same bug at v.2.3.5 
[main.log](https://github.com/DeFiCh/app/files/6478747/main.log)

**Comment by rolandwellinger** [comment] 2021-05-14 17:59
Yes i also have same problems. What is see is that the background process for blockchain sync takes a lot of mehr CPU power than in previous version 2.3.3. Maybe that causes the system instability. I also figured out that the Windows Firewall causes the issue. Maybe you do to many socketconnections. Check the Backgroundservices differences to previous version. Something does overhead there...

**Comment by rolandwellinger** [comment] 2021-05-14 18:03
@izzycsy 
please take care that 2.3.3 is keep working until new version runs stable. Do not update peer nodes or keep downward compatiblity for now. I think the more CPU/RAM and Even DISK Power a Computer has, the more stable it runs. On my High Powered Gaming Notebook Version 2.3.5 did not crash right now! On my Crypto PC with small power it does not work without the issues mentioned above. Try to create a testenvironment with System with less power and test it. Be sure Windows Firewall is ON! For any further Questions i'm here to help. Thanks

**Comment by rolandwellinger** [comment] 2021-05-14 18:05
@izzycsy 
You can create a VMPlayer VM-Machine with Windows 10 and give small Ressources to the Guest-System (3GB Ram, 1000 Mhz CPU, 1 Core and about 200GB for the Chain). I think you can reproduce it then. Cheers Roland

**Comment by m4rk88** [comment] 2021-05-14 18:06
Still the same in Version 2.3.5. on a ryzan 3600x, 64 GB RAM and 2x 2 TB NVME SSD

**Comment by rolandwellinger** [comment] 2021-05-14 18:07
> Still the same in Version 2.3.5. on a ryzan 3600x, 64 GB RAM and 2x 2 TB NVME SSD

OK interesting. Wich Windows Version you Run? => WINVER CMD => Function Update Version?

**Comment by m4rk88** [comment] 2021-05-14 18:08
![image](https://user-images.githubusercontent.com/84099086/118311404-258bc600-b4f0-11eb-9719-aff66dc615ae.png)

**Comment by Faucet1313** [comment] 2021-05-14 18:32
I have the same issue with 2.3.3 and 2.3.4 and 2.3.5. Using very large servers in 3 different hosting and locations with Windows Server 2016, and 2019 it not work well I always have this network error after few hours... and i have to restart the APP.  It would be very easy for the team to reproduce the issue i believe... As i have this issue with any version of the APP and any server...

**Comment by memzila** [comment] 2021-05-14 23:22
@Faucet1313 For me problems currently exist for 2.3.4 and 2.3.5. Version 2.3.3 works normally

**Comment by Faucet1313** [comment] 2021-05-14 23:27
![Network error 2 3 3](https://user-images.githubusercontent.com/83678739/118340673-b4163c80-b51c-11eb-9660-cc5dcb3ab0fa.png)
![server](https://user-images.githubusercontent.com/83678739/118340681-bb3d4a80-b51c-11eb-84c5-5eaa289f09b5.png)

**Comment by m4rk88** [comment] 2021-05-15 12:59
I downgraded yesterday to 2.3.3 and no more "Network Error" everything works finde for me with 2.3.3

**Comment by nordi6000** [comment] 2021-05-15 16:32
@izzycsy  I have the same problem after update from 2.3.3 to 2.3.5 
The wallet is going on error after 1-2 h and stop network.
Here my log files from the wallet...

[Error_2.3.5.zip](https://github.com/DeFiCh/app/files/6487767/Error_2.3.5.zip)

**Comment by Otti24xx** [comment] 2021-05-15 17:56
Same problem on Windows 10 on PC and on VPS (Windows 10 Enterprice)

**Comment by Stonygan** [comment] 2021-05-16 06:38
This problem is not new, we have it already at version 2.3.1 when SPV is enabled. https://github.com/DeFiCh/app/issues/644
With version >=2.3.4 SPV is enabled by default. See https://github.com/DeFiCh/app/commit/7d82d5a5313e4baa510b805dedc150e67aff57ee
We need urgent a fix, otherwise the Atomic Swap is not useable for this users. Please @all try following to ensure that this is really the problem:
Add spv=0 in your defi.conf (Windows: C:\Users\<username>\.defi\defi.conf") Im not sure in which section, add it at the top and under section [main].
Let us know if this solve the problem for now.
I have the same error with 2.3.5, add the switch yesterday and the last 12 hours nor errors.
@thedoublejay @izzycsy It seems that the SPV open to many connections, at some point the OS (or maybe the router?) dont have enough ports to handle this. Can we try to work with maxconnection or spv_maxconnection? Find no parameter to control it, maybe we need a possibility to do it.

**Comment by memzila** [comment] 2021-05-16 08:43
@Stonygan Thanks, i will try. I guess it is the windows firewall which goes down because other pc in same network with version 2.3.3 still works

**Comment by Otti24xx** [comment] 2021-05-16 11:41
It seems to work, Thank you!

Johannes Ott
Künkelsgasse 19
98574 Schmalkalden

03683 665384

Von: Stonygan
Gesendet: Sonntag, 16. Mai 2021 08:38
An: DeFiCh/app
Cc: Otti24xx; Comment
Betreff: Re: [DeFiCh/app] Network ERROR at new wallet 2.3.4 (#849)

This problem is not new, we have it already at version 2.3.1 when SPV is enabled. #644
With version >=2.3.4 SPV is enabled by default. See 7d82d5a
We need urgent a fix, otherwise the Atomic Swap is not useable for this users. Please @ALL try following to ensure that this is really the problem:
Add spv=0 in your defi.conf (Windows: C:\Users<username>.defi\defi.conf") Im not sure in which section, add it at the top and under section [main].
Let us know if this solve the problem for now.
I have the same error with 2.3.5, add the switch yesterday and the last 12 hours nor errors.
@thedoublejay @izzycsy It seems that the SPV open to many connections, at some point the OS (or maybe the router?) dont have enough ports to handle this. Can we try to work with maxconnection or spv_maxconnection? Find no parameter to control it, maybe we need a possibility to do it.

**Comment by rolandwellinger** [comment] 2021-05-16 13:14
@Stonygan What is SPV? And is there already an implementation of AtomicSwap. That whould be nice.

**Comment by rolandwellinger** [comment] 2021-05-16 13:15
@thedoublejay @Stonygan @izzycsy I fully agree here to Stony. I think the first system that fails with too much connections is the Windows Firewall Service. I noticed that a few time.

**Comment by izzycsy** [comment] 2021-05-16 16:12
Hi @Stonygan @Otti24xx @nordi6000 @rolandwellinger @m4rk88 @Faucet1313 , thanks for your feedback, please give us time to investigate the issue.

**Comment by nordi6000** [comment] 2021-05-16 16:30
@izzycsy I'm trying @Stonygan workaround and so far it works with no errors. Is working from this morning up to now.
![image](https://user-images.githubusercontent.com/49670309/118404662-1f265700-b674-11eb-9b5f-aad08e08d644.png)

**Comment by Faucet1313** [comment] 2021-05-16 17:30
@Stonygan Seems to work with spv=0. Thanks a lot.

**Comment by m4rk88** [comment] 2021-05-16 17:49
yes, spv=0 in defi.conf works fine for now

**Comment by OKnr66** [comment] 2021-05-16 18:37
Dear support,

System: W10

after upgrading to version 2.3.4 and 2.3.5 I got a NETWORK Error after some minutes (60-120 min) running the wallet. This seems to be not so hard, but also all browsers are concerned. This network error is also present during the resync and this is time robbing. Although the message "Network Error" appears, the wallet continues to sync, hä, although all browsers are dead (Chrome, Edge, Brave ....) . If you close the wallet during the sync, the network is back and all browsers are running. I heard in the chat, that I am not the only person with these problems. spv is not set.

Kind regards

Olaf Knauber

**Comment by M-Stege** [comment] 2021-05-16 20:13
OS: Win10 
free Space 603 GB
Defi-wallet: 2.3.5
i have the same problem and try now  _**spv=0**_

**Comment by HickYeah** [comment] 2021-05-16 22:47
i changed it to spv=0 and won't work! On v2.3.5, any suggestions! Location is US

[2021-05-16 18:44:52.342] [IPC-RENDERER-error] [isBlockchainStarted] "Request failed with status code 503"

**Comment by thedoublejay** [comment] 2021-05-17 01:32
Hi all, we are currently investigating this issue regarding network disconnection. As @Stonygan reported, SPV is not enabled by default since >=2.3.4. We have removed it on the builds due to some reports of network disconnection. It seems that the network disconnection might not be due to spv only as some users report that they still encounter this issue even with SPV disconnected. Will continue investigating this issue and will update this thread once bug has been identified. Thank you.

**Comment by memzila** [comment] 2021-05-17 08:56
Hi @Stonygan , looks like working after setting spv=0. Keept it running over night and no network errors so far.

**Comment by rolandwellinger** [comment] 2021-05-17 08:57
@memzila @Stonygan Nice, i'll give it a try too. Thanks for your tests.

**Comment by Faucet1313** [comment] 2021-05-17 12:35
Bad surprise today. Finally got the network error with spv=0 and version 2.3.5

**Comment by Stonygan** [comment] 2021-05-17 13:27
> Hi all, we are currently investigating this issue regarding network disconnection. As @Stonygan reported, SPV is not enabled by default since >=2.3.4. We have removed it on the builds due to some reports of network disconnection. It seems that the network disconnection might not be due to spv only as some users report that they still encounter this issue even with SPV disconnected. Will continue investigating this issue and will update this thread once bug has been identified. Thank you.

Thanks for the info, you are right, code is excluded, but SPV is already active without spv=0. When i start the current downloadable 2.3.5 APP without explicit spv=0 in the conf and type spv_syncstatus in the CLI, i get infos see below.
When spv=0 is in the defi.conf, i got the message SPV are disabled when i run spv_syncstatus.
Its a strange error, hope we can find a solution together.

![image](https://user-images.githubusercontent.com/44975826/118495855-e2b23400-b723-11eb-9a07-9bd7748c1753.png)

I have no problems with network errors over 36hours now, when i set spv=0.

**Comment by Stonygan** [comment] 2021-05-17 13:33
![image](https://user-images.githubusercontent.com/44975826/118497143-1772bb00-b725-11eb-97c6-09dacc9c8fd1.png)
With 2.3.3 and without spv=0, spv is disabled by default, 2.3.5 its enabled.

**Comment by thedoublejay** [comment] 2021-05-18 00:16
Sure thanks for your help @Stonygan! Will be investigating this issue

**Comment by Faucet1313** [comment] 2021-05-18 01:55
A lot more stable with spv disabled. Now i have this network error only once a day. Before i had to restart the wallet 3-4 time daily.

![SPV](https://user-images.githubusercontent.com/83678739/118578656-d57d5f80-b78c-11eb-94cb-e8cc483a30c3.png)
![Error logs](https://user-images.githubusercontent.com/83678739/118578675-dc0bd700-b78c-11eb-957f-3abfe8995441.png)

**Comment by memzila** [comment] 2021-05-18 06:57
Hi @Faucet1313 . I think the config has not worked for you, because when i give in the command it shows the following
![sync](https://user-images.githubusercontent.com/48082176/118605486-a1b72f80-b7b6-11eb-9474-ced935fc0ef3.PNG)


Configfile i use:
rpcauth=some string
rpcuser=some string
rpcpassword=some string
datadir=D:\defichain
rpcconnect=127.0.0.1
testnet=0
regtest=0

[main]
wallet=Wallet.dat
walletdir=D:\defichain
datadir=D:\defichain
rpcbind=127.0.0.1
rpcport=8555
spv=0

[test]
rpcbind=127.0.0.1
rpcport=8555

**Comment by Faucet1313** [comment] 2021-05-18 19:07
@memzila you are right. Now i have the same result. Thank you.

**Comment by HickYeah** [comment] 2021-05-19 13:38
guys any updates regarding this issue?

**Comment by rolandwellinger** [comment] 2021-05-19 17:49
No success here. SVP=0 !!! Still stopping Chain Sync after a while....

**Comment by memzila** [comment] 2021-05-19 17:57
@rolandwellinger add it exactly as in my config example. And what say the command spv_syncstatus?

**Comment by yungmann** [comment] 2021-05-19 22:35
Guys i do have the same ptoblem as you do, 2.3.5 simply won't sync the blockchain at all, whatever the tricks i try to throw a it

Any help maybe ?

**Comment by thedoublejay** [comment] 2021-05-20 02:08
We're still investigating the node issue. It's not an app issue but on the node side. We'll update you once we got a fix from the node side. 

In case you're facing this. you can follow @Stonygan's workaround to disable SPV (spv=0 on [main]) in your `defi.conf`.

**Comment by Faucet1313** [comment] 2021-05-20 02:24
Yes. Regarding the nodes, sometime i have this issue below and when i check the logs i see the same "Network error"

![Node discconected](https://user-images.githubusercontent.com/83678739/118909129-d942ea80-b922-11eb-8e9e-3ef67e7bc4e0.png)

**Comment by Faucet1313** [comment] 2021-05-20 21:43
Today when i had the network error i shutdown the wallet like usual and i checked if there is still some active processses and i saw defid still active and use a lot of RAM and no way to kill the process.
![RAM](https://user-images.githubusercontent.com/83678739/119052246-9a657100-b9c4-11eb-868e-42216a554eba.png)

**Comment by Faucet1313** [comment] 2021-05-24 00:11
Is linux affected by this error ?

**Comment by thedoublejay** [comment] 2021-05-24 13:50
Hi, there's a potential fix from the node side for this issue. You can check it from this PR https://github.com/DeFiCh/ain/pull/424.

**Comment by izzycsy** [comment] 2021-05-28 10:39
Hi @supervolot @m4rk88 @memzila @Faucet1313 @rolandwellinger @nordi6000 @Stonygan @Otti24xx @M-Stege @HickYeah @yungmann , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by Faucet1313** [comment] 2021-05-29 19:15
Hello, @izzycsy, Thanks for the update. Regarding the mandatory upgrade i got confused even after reading the release note. So wallet user app just need to install the last version, download the snapshot and retstart the masternodes that enough ?

**Comment by izzycsy** [comment] 2021-05-30 18:58
Hi @Faucet1313 , yes you need to update before the Eunos Upgrade which would happen block 894,000 (ETA 03 June 2021). The latest version as of 31 May 2021 is v2.4.0.

**Comment by Faucet1313** [comment] 2021-06-01 19:04
Hi guys, On my side no more network error or node disconnected since v2.4.0.

**Comment by izzycsy** [comment] 2021-06-02 12:46
Hi @supervolot @m4rk88 @memzila @Faucet1313 @rolandwellinger @nordi6000 @Stonygan @Otti24xx @M-Stege @HickYeah @yungmann , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Closed by izzycsy** 2021-06-02 12:46 UTC
Labels: kind/bug, os/win, triage/accepted, version/2.3.4
