### ISSUE TITLE
Unable to send BTC / ETH / USDT

### ISSUE THREAD

**Issue by jonjomatic** [DeFiCh/app#195] opened 2020-12-29 01:44 UTC
I am trying to transfer all my coins back to cake since I can't add more liquidity to LPs in defi-app 2.1.4

USDT transfer ok.  DFI transfer ok. Still have a few DFI in defi-app wallet.  

Issue: BTC transfer won't go.  Error is below.

![image](https://user-images.githubusercontent.com/75774679/103252840-7d9ab380-49b9-11eb-86ad-6c0c15b5704f.png)

I think I have enough DFI to pay for the transfer - I followed Daniel Zirkel's instructions to convert DFI tokens to coins

![image](https://user-images.githubusercontent.com/75774679/103253034-67412780-49ba-11eb-9fef-448b5f06b8f9.png)

**Comment by jonho79** [comment] 2020-12-29 02:41
I'm having the same issue with BTC withdrawals.  Tried multiple times using multiple amounts over the past hour.  I get the same issue for ETH and USDT transfers as well.

**Comment by izzycsy** [comment] 2020-12-29 19:10
Hi @jonjomatic , thanks for your feedback & screenshot. Could you kindly send your app logs. Please give us time to investigate this issue. 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103308070-87b9c200-4a4c-11eb-924f-e6273b940679.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/103308073-89838580-4a4c-11eb-8c0d-7b374bd9ed33.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/103308083-8c7e7600-4a4c-11eb-8817-40e4bf8e9e03.png">

**Comment by jonho79** [comment] 2020-12-29 19:17
Hi,

The app logs should be included as a zip file attachment in my prior email.  I can resend if you don’t have them.

Regards,

Jon

**Comment by jonho79** [comment] 2020-12-29 19:53
Here you go

**Comment by izzycsy** [comment] 2020-12-30 11:01
Hi @jonho79 , all right. I've informed the team to look out for your email. Alternatively, you can drag and drop it here so I can escalate this. Thank you.

**Comment by jonho79** [comment] 2020-12-30 14:19
[App Logs JH.zip](https://github.com/DeFiCh/app/files/5754485/App.Logs.JH.zip)

**Comment by jonho79** [comment] 2020-12-30 14:20
OK drag and dropped app log

**Comment by izzycsy** [comment] 2020-12-31 06:29
Hi @jonho79 , well received, please give us time to investigate this issue. Thank you.

**Comment by sudden-break** [comment] 2020-12-31 10:18
Same issue here but with USDT

**Comment by jonjomatic** [comment] 2021-01-01 08:11
Hi - attached my logs now

[app logs 20210101.zip](https://github.com/DeFiCh/app/files/5758711/app.logs.20210101.zip)

**Comment by sudden-break** [comment] 2021-01-01 11:18
It is working with version 2.1.3

**Comment by jonjomatic** [comment] 2021-01-02 04:02
> 
> 
> It is working with version 2.1.3

I rolled back to 2.1.3 and it didn't work for me

**Comment by jonjomatic** [comment] 2021-01-02 04:06
Some more logs @izzycsy - Also cannot transfer DFI out now, though I did manage to swap BTC -> DFI on the DEX in defi-app 2.1.4

[app log 20200102.zip](https://github.com/DeFiCh/app/files/5759744/app.log.20200102.zip)

**Comment by izzycsy** [comment] 2021-01-02 09:19
@jonjomatic well received, please give us time to investigate this. In the mean time, there’s a temporary solution to this, it could be that you've too little DFI UTXOs balance — which is required to perform swap and other functions. You could try convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

**Comment by telefonjoker** [comment] 2021-01-03 13:10
Hi izzycsy,

I have the same issue to send my BTCTOKEN to Cake. This my error-message: Not enough balance on wallet accounts, call utxostoaccount to increase it. Can i send you my logfiles?

**Comment by TTSIP** [comment] 2021-01-03 13:34
Hi,

I have the same issue with version 2.1.4 cant transer DBTC out of DEFI App to cake

![image](https://user-images.githubusercontent.com/76814941/103479847-c34be780-4dd0-11eb-809a-7fb925285358.png)


BR

**Comment by izzycsy** [comment] 2021-01-04 11:33
Hi @jonjomatic @jonho79 @sudden-break @telefonjoker @TTSIP , thanks for your feedback. 
Update is out! <https://defichain.com/downloads/> 
 Please give a thumbs up to this comment if your issue has been resolved, if not, please send your app logs and we'll further investigate.

**Comment by telefonjoker** [comment] 2021-01-04 13:02
Hi izzycsy,

thank you for your recommendation. But the problem still exists with the version 2.1.5. How can I send you the app logs?

**Comment by TTSIP** [comment] 2021-01-04 13:04
For me the same still exists with 2.1.5 i have 4 real DFI in the app so transaction fee is covered

Do we have to do something with the new version or just update it ?

BR

**Comment by jonjomatic** [comment] 2021-01-04 14:49
Hi @izzycsy - Happy new year to you.

Same for me, the update to v2.1.5 doesn't resolve the issue and confirm I have DFI coins (below).  Have attached the latest app log.  I couldn't attach the binary, even when zipped, github said the file is too big. Cheers.

```
>getbalance
11.00087626
```

[app log 20210104.log](https://github.com/DeFiCh/app/files/5765235/app.log.20210104.log)

**Comment by izzycsy** [comment] 2021-01-04 14:53
Hi @telefonjoker a guide on how-to-attach logs are in the comment at the beginning. Simply drag and drop. Uou'll have to use the temporary method if the error still persists <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>. Please give the team to continue to look into it. Will await for your logs. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/103547567-891d3b80-4edf-11eb-8cce-a9367881c300.png">

**Comment by izzycsy** [comment] 2021-01-04 14:55
Hi @TTSIP , on the top right hand corner of your app, there should be an update button, if not you can replace it by downloading it from <https://defichain.com/downloads/>.

**Comment by izzycsy** [comment] 2021-01-04 14:57
Hi @jonjomatic , happy new year to you too. Well received, I'll update the team on the latest app log sent. Thank you.

**Comment by telefonjoker** [comment] 2021-01-04 15:00
Hi Izzycsy,

here are my logs. Thank you for your efforts.

[Archiv.zip](https://github.com/DeFiCh/app/files/5765308/Archiv.zip)

**Comment by TTSIP** [comment] 2021-01-04 17:08
> Hi @TTSIP , on the top right hand corner of your app, there should be an update button, if not you can replace it by downloading it from https://defichain.com/downloads/.

Hi here u have the logs



[Apploggs.log](https://github.com/DeFiCh/app/files/5765893/Apploggs.log)
[Binary.log](https://github.com/DeFiCh/app/files/5765896/Binary.log)

The Converting makes no sence ... because the issue is not that i would not have DFI coins ... i have the issue is that DBTC cant be withdrawen from APP to Cake ... (With DETH it works)

BR

**Comment by kwamelaryea** [comment] 2021-01-04 22:12
I have the same issue but my send button is greyed out and inactive, help please. 

[app_logs.log.zip](https://github.com/DeFiCh/app/files/5766991/app_logs.log.zip)

![Screenshot 2021-01-04 at 18 04 26](https://user-images.githubusercontent.com/3295096/103584793-4b6de200-4ee2-11eb-9fca-2c15ebad1a9a.png)

**Comment by AlanAdamson** [comment] 2021-01-05 06:21
Not sure if this is related but I was having the same issue, not being able to send BTC from the app. With version 2.1.5 I was able to get the app to say the BTC was sent but have not received into cake after an hour. The app stopped loading transactions so tried closing/re-opening and now can't get app to load again. I was able to find the transaction on blockchain explorer though: https://explorer.defichain.com/#/DFI/mainnet/tx/8c1cc5651285582c9ea4d9e6ff3dcf0c3448ee6ce2cc0065d4a8fa264cb984e6

**Comment by jonho79** [comment] 2021-01-05 06:29
Updated to 2.1.5

Issue is still persisting and I am getting this statement "Not enough balance on wallet accounts, call utxostoaccount to increase it."

Here are my logs

[App Log JH.zip](https://github.com/DeFiCh/app/files/5768480/App.Log.JH.zip)

**Comment by izzycsy** [comment] 2021-01-05 12:04
Hi @kwamelaryea & @AlanAdamson , thanks for your feedback. Your issue seems different, let me link you to the right on <https://github.com/DeFiCh/app/issues/123>. @kwamelaryea App logs are well received, please give us time to investigate. For future comments regarding _unable to send coin_, please comment in the link provided. Thank you.

**Comment by izzycsy** [comment] 2021-01-05 12:05
Hi @jonho79 , thank you for the update. Well received, please give us time to investigate. Thank you for your understanding.

**Comment by MadqaZ** [comment] 2021-01-05 12:33
Same issue for me ever since v2.1.4
Swapped DFI tokens to coins following the reddit guide.

DFI to Cake = No problem.
ETH to Cake = "Not enough balance on wallet accounts, call utxostoaccount to increase it."
BTC to Cake = Haven't tried it yet.

App Log:
[app-log.zip](https://github.com/DeFiCh/app/files/5770092/app-log.zip)

Bin Log (in a 4x10mb zip file):
***!! Had to rename files for github upload file support. Rename files to: 
bin-log-zip.001, bin-log-zip.002, bin-log-zip.003, bin-log-zip.004**
[bin-log.001.zip](https://github.com/DeFiCh/app/files/5770098/bin-log-001.zip)
[bin-log-002.zip](https://github.com/DeFiCh/app/files/5770099/bin-log-002.zip)
[bin-log-003.zip](https://github.com/DeFiCh/app/files/5770100/bin-log-003.zip)
[bin-log-004.zip](https://github.com/DeFiCh/app/files/5770101/bin-log-004.zip)

**Comment by Workoholic-Jap** [comment] 2021-01-06 10:32
Same problem. Cannot transfer BTC to Cake. Same error message.
[applogs.zip](https://github.com/DeFiCh/app/files/5775247/applogs.zip)

**Comment by jonjomatic** [comment] 2021-01-07 03:29
Hi @izzycsy @uzyn  - Is there any update to share?  Or is there a CLI workaround?

A bit uncomfortable to know that funds can't be moved if needed.

**Comment by izzycsy** [comment] 2021-01-07 05:47
Hi @MadqaZ , app log well received, however I'm unable to open the binary logs. I've forwarded your app log to the team anyway. 

@Workoholic-Jap , I'm unable to open your `.zip` file, could you resend them please? Thank you. 

@jonjomatic I do not have CLI workaround at the moment. I apologise for the delay. The team is trying to fix the issue. 

Thank you all for your patience.

**Comment by MadqaZ** [comment] 2021-01-07 16:45
Hi @izzycsy How useful is the bin.log file for the team in terms of trying to figure out this issue? Do you really need it?

The bin.log file is ~150Mb, too big to share on Github, so other than zipping and splitting it into 10Mb volumes, all that is left is sharing it through something else than Github. I can make you a WeTransfer link, for example.

I just tested the file, and it works fine, although I do pack/unpack it with 7zip (https://www.7-zip.org/), not with the standard Windows compressor, since that one doesn't seem to recognize the split volume sequence. Also remember to rename the files as I mentioned before ;)

**Comment by telefonjoker** [comment] 2021-01-07 16:49
Hi izzycsy,

have you now been able to localize the problem?

BR
Claus

**Comment by MadqaZ** [comment] 2021-01-08 13:03
Update: v2.1.6

- Still the same error when trying to send ETH to Cake account.
- Still have to re-index at startup

[app-log.zip](https://github.com/DeFiCh/app/files/5787317/app-log.zip)

**Comment by TTSIP** [comment] 2021-01-08 17:45
@izzycsy for your information:

The mistake comes up if u use teh dex in both ways: Example u swap DFI to BTC and afterwards u swap BTC to DFI 

If u only swap it in one way withdraw works ... if u use both directions not.

Perhaps this helps the developers

Thanks

BR

**Comment by MadqaZ** [comment] 2021-01-08 18:09
@TTSIP Interesting. I did use the Dex to swap DFI to BTC, but not the other way around. But I did swap ETH to DFI.

**Comment by telefonjoker** [comment] 2021-01-09 08:56
Hi @izzycsy 
I found a solution for me. 
my problem was that my tokens were spread over two addresses. One of these addresses was no longer visible, but a large part of the BTC tokens were stored on it. I created this address again in the app with "create new address". I deselected the button "Automatically create a new address" and was able to enter the old address again. "Now there was the following problem. Only BTC tokens and no DFI tokens were on this address. That's why I kept a small LM BTC-DFI in which the rewards were paid out exactly to this address. I now waited until the reward totaled 0.01 DFI. Now it is again possible to transfer this BTC token to Cake. The solution is that all addresses must have at least 0.01 DFI. Realizing this is unfortunately not easy.

**Comment by izzycsy** [comment] 2021-01-11 17:31
Hi @AlanAdamson @MadqaZ , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if the synchronisation issue has been resolved. Thank you.

**Comment by izzycsy** [comment] 2021-01-11 17:43
Update: The following issues are under investigation. Please give a thumbs down to confirm that I tagged you correctly in the issue you're facing, hope I didn't miss anyone out. Thank you.

`Unable to send BTC`
@jonjomatic @jonho79 @kwamelaryea @Workoholic-Jap @TTSIP 

`Unable to send ETH`
@MadqaZ 

`Unable to send USDT`
@sudden-break 


For those that have not tried this, below are steps on how to transfer your coins from DeFi app to via <cakedefi.com>, you may try sending a small amount first to test.

1. Click on **Balances** in <cakedefi.com>
2. In the BTC row, click on **Deposit** button
3. You'll see the **Transfer Network** options `BTC` / `DeFi Blockchain`
4. Under the QR Code states your DeFi address, **copy** it
5. Go to DeFi app > BTC wallet > Send
6. **Paste** your DeFi address into `To address` field

**Comment by kwamelaryea** [comment] 2021-01-11 19:10
Thanks for the update @izzycsy logs attached below
[app-logs.log.zip](https://github.com/DeFiCh/app/files/5797821/app-logs.log.zip)

**Comment by MadqaZ** [comment] 2021-01-11 23:33
@izzycsy Unable to send **ETH & BTC** for me ;)

**Comment by jonho79** [comment] 2021-01-12 06:37
Not only am I unable to set BTC, I also can't send ETH or USDT.  I get the same error message for the failed transfers.

"Not enough balance on wallet accounts, call utxostoaccount to increase it."

**Comment by izzycsy** [comment] 2021-01-12 07:22
Hi @kwamelaryea , thanks for the latest log. 

Hi @MadqaZ @jonho79 , could you resend your logs please? 

Thanks for replying, the team is currently investigating the issue. Thank you for your patience.

**Comment by MadqaZ** [comment] 2021-01-12 07:41
@izzycsy 
[app-log-2.1.6.log.zip](https://github.com/DeFiCh/app/files/5800474/app-log-2.1.6.log.zip)

**Comment by telefonjoker** [comment] 2021-01-12 09:30
Sorry @izzycsy,

now I have the same problem as last week again. Not enough balance on wallet accounts, call utmost-account to increase it. But the accounts have enough amounts for me. 
![image](https://user-images.githubusercontent.com/76906682/104295185-66cb8500-54c0-11eb-8414-39fb4c3b8104.png)
Should I send you the Logfiles again?
BR
Claus

**Comment by izzycsy** [comment] 2021-01-12 10:13
Hi @telefonjoker , thanks for your feedback. Yes please send your logs. May I know which coins are you unable to send?

**Comment by telefonjoker** [comment] 2021-01-12 11:11
Hi @izzycsy, I would like to send the BTC´s to Cake. Here are my Logfiles.

BR
Claus
[Logs_telefonjoker.zip](https://github.com/DeFiCh/app/files/5801626/Logs_telefonjoker.zip)

**Comment by izzycsy** [comment] 2021-01-12 22:03
Hi @jonjomatic @jonho79 @kwamelaryea @Workoholic-Jap @TTSIP @MadqaZ @telefonjoker @sudden-break , sharing what @DanielZirkel posted recently, a temporary workaround for this issue, attached is the link that might help you <https://www.reddit.com/r/defiblockchain/comments/kvsw4l/stepbystep_workaround_sending_btc_eth_usdt_and/>. Do update if it worked for you. The team is trying to fix this issue, thank you for your patience.

**Comment by jonho79** [comment] 2021-01-13 06:56
Hi all,

I can confirm that the work around through the console that DanielZirkel posted on reddit does work.  I was able to transfer some BTC back into my Cake account.  I havent tried for ETH or USDT but plan to in the next few days.  Thanks for alerting me to the work around,  much appreciated

Regards,

Jon

**Comment by MadqaZ** [comment] 2021-01-13 14:19
@izzycsy I see issues is being closed, but just to confirm, the workaround works for ETH too. Just successfully send some to my Cake account. Thank you all for the help!

**Comment by jonjomatic** [comment] 2021-01-13 15:03
I tried to test the CLI workaround this afternoon by sending some DFI to cake.

Got a tx hash output OK.

So far it hasn't been acknowledged by cake as it usually would on receipt. Have sent to this cake DFI address from defi-app before.

Maybe there is a backlog for deposits at cake so will check again tomorrow.

-------- Original Message --------

**Comment by izzycsy** [comment] 2021-01-13 16:04
Hi @jonjomatic @jonho79 @kwamelaryea @Workoholic-Jap @TTSIP @MadqaZ @telefonjoker @sudden-break @Huzi1988 @mikej289 @floxcgncgn , update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.

**Comment by telefonjoker** [comment] 2021-01-13 19:14
@izzycsy,

it works for me!
Thank you!

**Comment by MarsaXod** [comment] 2021-01-13 21:06
Good day support,
After the last update, I got a new message while transferring DEFI tokens in the console. Pls see attached
[error.txt](https://github.com/DeFiCh/app/files/5811064/error.txt)
[App_config.zip](https://github.com/DeFiCh/app/files/5811078/App_config.zip)

**Comment by kwamelaryea** [comment] 2021-01-14 09:45
Hi @izzycsy the workaround doesn't work for me, it appears to be an address validation issue. 
I have updated to version 2.1.7 but now I have some sync issues but I am restarting the wallet again to see if I can fix.
![Screenshot 2021-01-13 at 18 07 02](https://user-images.githubusercontent.com/3295096/104573615-60224680-5655-11eb-8d43-eea9c2ec2bf2.png)

**Comment by MarsaXod** [comment] 2021-01-14 11:30
> Good day support,
> After the last update, I got a new message while transferring DEFI tokens in the console. Pls see attached
> [error.txt](https://github.com/DeFiCh/app/files/5811064/error.txt)
> [App_config.zip](https://github.com/DeFiCh/app/files/5811078/App_config.zip)

After a recent update to 2.1.8 still has the same issue, ps see attached log and error text file.
[app_log_2.1.8.log.zip](https://github.com/DeFiCh/app/files/5814103/app_log_2.1.8.log.zip)
[defi 2.1.8 error.txt](https://github.com/DeFiCh/app/files/5814105/defi.2.1.8.error.txt)

**Comment by kwamelaryea** [comment] 2021-01-14 16:50
Hi @izzycsy 
Can I reopen this issue, please? I have updated the app to version 2.1.7 but I still have the same issue. However, now I can't use the DEX to convert my BTC back to DFI and I get the following error "recipient () does not refer to any valid address" also the app hangs a bit on boot up and I get an unresponsive white screen. 

![Screenshot 2021-01-14 at 11 45 12](https://user-images.githubusercontent.com/3295096/104621897-e60fb300-5690-11eb-9148-d97491ffa912.png)

I have attached new app logs
[app_logs.log.zip](https://github.com/DeFiCh/app/files/5815749/app_logs.log.zip)

**Comment by MarsaXod** [comment] 2021-01-14 17:12
> Hi @izzycsy
> Can I reopen this issue, please? I have updated the app to version 2.1.7 but I still have the same issue. However, now I can't use the DEX to convert my BTC back to DFI and I get the following error "recipient () does not refer to any valid address" also the app hangs a bit on boot up and I get an unresponsive white screen.
> 
> ![Screenshot 2021-01-14 at 11 45 12](https://user-images.githubusercontent.com/3295096/104621897-e60fb300-5690-11eb-9148-d97491ffa912.png)
> 
> I have attached new app logs
> [app_logs.log.zip](https://github.com/DeFiCh/app/files/5815749/app_logs.log.zip)

Try the latest, version 2.1.9 is available already

**Comment by MarsaXod** [comment] 2021-01-14 17:15
> > Good day support,
> > After the last update, I got a new message while transferring DEFI tokens in the console. Pls see attached
> > [error.txt](https://github.com/DeFiCh/app/files/5811064/error.txt)
> > [App_config.zip](https://github.com/DeFiCh/app/files/5811078/App_config.zip)
> 
> After a recent update to 2.1.8 still has the same issue, ps see attached log and error text file.
> [app_log_2.1.8.log.zip](https://github.com/DeFiCh/app/files/5814103/app_log_2.1.8.log.zip)
> [defi 2.1.8 error.txt](https://github.com/DeFiCh/app/files/5814105/defi.2.1.8.error.txt)

After update 2.1.9, the same thing : Add-on auth TX failed: Insufficient funds

**Comment by MarsaXod** [comment] 2021-01-15 09:34
> > > Good day support,
> > > After the last update, I got a new message while transferring DEFI tokens in the console. Pls see attached
> > > [error.txt](https://github.com/DeFiCh/app/files/5811064/error.txt)
> > > [App_config.zip](https://github.com/DeFiCh/app/files/5811078/App_config.zip)
> > 
> > 
> > After a recent update to 2.1.8 still has the same issue, ps see attached log and error text file.
> > [app_log_2.1.8.log.zip](https://github.com/DeFiCh/app/files/5814103/app_log_2.1.8.log.zip)
> > [defi 2.1.8 error.txt](https://github.com/DeFiCh/app/files/5814105/defi.2.1.8.error.txt)
> 
> After update 2.1.9, the same thing : Add-on auth TX failed: Insufficient funds

Hi @izzycsy, any news about above

**Comment by uzyn** [comment] 2021-01-17 03:08
@kwamelaryea It appears that you are attempting to send BTC to a Bitcoin network address. BTC on DeFiChain is a DeFi Standard Token (DST) that is only transmittable to other DeFiChain addresses (usually starting with `8` or `d`).

Do swap from DST BTC to BTC on Bitcoin, you can go through sites like cakedefi.com or swap DST BTC to DFI on DEX.

**Comment by izzycsy** [comment] 2021-01-18 07:18
Hi @MarsaXod @kwamelaryea , update v2.1.10 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, kindly send new information (include screenshots) and app logs. Thank you.

**Comment by 1230-1** [comment] 2021-01-18 09:09
hi all, need help. I am unable to swap DFI for BTC via Dapp. Any advise? 

[Defi App log.log](https://github.com/DeFiCh/app/files/5829014/Defi.App.log.log)
![image](https://user-images.githubusercontent.com/77612073/104894507-c5589d80-59af-11eb-9f26-b118c3980cdc.png)
![image](https://user-images.githubusercontent.com/77612073/104894591-dbfef480-59af-11eb-9558-5abd33ef2285.png)

**Comment by izzycsy** [comment] 2021-01-18 09:44
Hi @1230-1 , thanks for the screenshots and feedback, you're facing this issue `DEX: recipient () does not refer to any valid address`, I'll link you to <https://github.com/DeFiCh/app/issues/305> which we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding. 

Logs well received.

**Comment by rxandr** [comment] 2021-01-23 01:22
I cannot send out, the continue button doesn't light up to be selected, something is bad with lots of money in the balance=/

**Comment by izzycsy** [comment] 2021-01-24 16:43
Hi @kwamelaryea @MadqaZ @rxandr , update v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, kindly provide with new information on your app's behaviour (include screenshots) and app logs. Thank you.

**Closed** 2021-01-27 11:16 UTC
Labels: bug, first issue
