### ISSUE TITLE
Wallet not created

### ISSUE THREAD

**Issue by Alex080988** [DeFiCh/app#149] opened 2020-12-20 00:10 UTC
Hi yesterday i installed the DeFi Chain App.
After 45min Synchonisizing i created a wallet. 
Wrote down the 24 word for recovering.
Today I just wanted to see, if my amount of 
crypto was send. But now i cannot find the wallet
and cannot restore it there is just "New wallet" or
"restore wallet" -> restoring is not working. It is coming the note:

>>Already have this key (either as an HD seed or as a loose private key)<<

So where can i see my wallet

**Comment by izzycsy** [comment] 2020-12-21 09:59
Hi @Alex080988 , thanks for your feedback. To understand your user flow better, after you created wallet the screen displayed is still on `Create / Restore Wallet screen`? Similar to this issue? <https://github.com/DeFiCh/app/issues/150>

Please give us time to investigate this.

**Comment by izzycsy** [comment] 2020-12-24 11:22
Hi @Alex080988 , may I know if the issue is resolved with the new update v2.1.4?
https://github.com/DeFiCh/app/releases/tag/v2.1.4

**Comment by nappy** [comment] 2021-01-03 23:05
Same issue here with 2.1.5

**Comment by izzycsy** [comment] 2021-01-04 12:11
Hi @Alex080988 @nappy , update v2.1.5 is officially out <https://defichain.com/downloads/>. 
Please give a thumbs up to this comment if your issue has been resolved, if not, please send your app logs and we'll further investigate.

**Comment by nappy** [comment] 2021-01-05 11:20
Seems to be resolved, at least with 2.1.5 (clean app data) I was able to restore from seed.

On a side note though, there is probably already an issue for this, the full chain is still being re-downloaded after each application start with release 2.1.5.

**Comment by izzycsy** [comment] 2021-01-11 09:56
Hi @Alex080988 @nappy , , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.

**Closed by izzycsy** 2021-01-11 09:56 UTC
Labels: bug, pending
