### ISSUE TITLE
Error: ReserveKeyFromKeyPool: unknown key in key pool

### ISSUE THREAD

**Issue by saibot600** [DeFiCh/app#990] opened 2021-07-07 19:24 UTC
#### Actual behavior: 
I am getting this error in my wallet when trying to swap, liquidity mine or send funds: "ReserveKeyFromKeyPool: unknown key in key pool". 

#### Expected behavior: 

No errors.

#### How to reproduce it (as minimally and precisely as possible): 

No idea how or why this even appeared. This wallet has never had any problems for about 6 months and suddenly this error appeared. I did all the usual stuff (restarting, importing the wallet again, renaming the wallet file etc.) but to no avail. Also, an older file version of this wallet (from another backup) caused the same error. I have a second wallet file on my computer (not a backup but a different wallet) which works without this error by the way.

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.2
- Operating System (OS): Win 10
- Current free storage capacity: 230GB

#### Anything else we need to know?

During my testing, at one point I think I was able to get the private keys through the dumpprivkey command without even unlocking the wallet but now I can't reproduce it anymore. So, maybe something is wrong with the encryption somehow.

I obviously don't want to lose any funds. I've also found this thread in Bitcointalk forum but I don't know if this applies here in some way as well: https://bitcointalk.org/index.php?topic=5039507.0

Thanks a lot for your help!

![grafik](https://user-images.githubusercontent.com/87093515/124816579-f5e5c100-df68-11eb-8b2b-3c9bfde99e21.png)
![grafik](https://user-images.githubusercontent.com/87093515/124816767-304f5e00-df69-11eb-8015-a7459ed475c3.png)

**Comment by izzycsy** [comment] 2021-07-08 08:33
Hi @saibot600 , some suggestions that might help, I suggest not to rename your `wallet.dat` files, or move it when the app is running. If anything, 
1. create a new wallet backup, specify your preferred name for the file, select your preferred folder and then save.  
2. copy and paste the wallet.dat to another folder for safe keeping 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/124889738-f4200a00-e009-11eb-889a-7cd65b4797fa.png">

<img width="1018" alt="Select folder to backup wallet1" src="https://user-images.githubusercontent.com/65014479/124888041-511ac080-e008-11eb-904b-2d203fa8ce59.png">

<img width="1021" alt="Select folder to backup wallet2" src="https://user-images.githubusercontent.com/65014479/124888054-5415b100-e008-11eb-9db3-6c529b36c390.png">

Thanks for doing some investigation. Regarding `"ReserveKeyFromKeyPool: unknown key in key pool"`, according to the link you sent, it could be a corrupted wallet.dat, I would suggest you to try and move your funds. 

Can you send your logs please? It'll help us understand and confirm the issue. 
<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/124889058-46146000-e009-11eb-971a-e3eeded70a8d.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/124889074-49a7e700-e009-11eb-8948-4268b9105fca.png">

——————————————————————
In the mean time,  can you try other `wallet.dat` files? In the `wallets` folder you'll likely see `wallet-bak-123456789` as well, these are additional wallet backups. Try those. 

For Windows it's located here:  
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/124889308-8b389200-e009-11eb-96b8-2e0b0521dfe6.png">

You may refer to the following steps on how to **Restore Wallet via Backup**:

#### 1. Ensure app is 100% synchronized (green tick at bottom left hand corner), select `Restore wallet via backup` (wallet.dat)

<img width="1017" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/123794687-b50cfd00-d915-11eb-9950-a797b5b6e5c0.png">


#### 2. A window should pop up, direct the app to your `wallet.dat` location
• In the wallets folder you'll likely see wallet-bak-123456789 as well, these are additional backups. 
• Select the `wallet.dat` 
***Note: the `wallets` folder is a default location and should not be moved**

<img width="1016" alt="Restore   Select folder of backup1" src="https://user-images.githubusercontent.com/65014479/123795070-2ea4eb00-d916-11eb-9af3-ee436bba7c30.png">


#### 3. Another possible scenario, could be that you saved it in another folder. 
• For example, I saved the `wallet backup` in `Documents/_BACKUP`
• Hence, I'd **redirect** the app to the folder `Documents/_BACKUP`, and select the `wallet.dat`

<img width="1019" alt="Restore   Select folder of backup2" src="https://user-images.githubusercontent.com/65014479/123795291-73308680-d916-11eb-9dc6-73d0240c8678.png">

**Comment by saibot600** [comment] 2021-07-08 17:03
Thank you very much for your help. Through that I think I was able to solve it by now. What I did:

- There were no working "bak" backup files in my folder (according to your description) unfortunately. Only one file with ".bak" extension but this one didn't work, neither when I manually changed the extension to ".dat".
- Creating a new wallet backup and trying it from that one did not solve the problem.
- Yet I remembered another backup from about 4 months ago I had made from the wallet file (a newer backup had also failed). With that file it finally worked and the error hasn't appeared anymore so far.

Remaining questions:

1. Is it actually necessary to continuously make backups of the wallet file or should one backup be enough as the wallet file is ideally not changed afterwards anymore by the app?
2. I wonder how the wallet file got corrupted in the first place. Perhaps it has to do with an automated file backup solution I am using and some bad coincidence or so. Or anything that is more likely than that?
3. Do you still need any logs etc. or only in case the error appears again?
4. Should I still move all my funds to a new wallet or should it be ok now as there is no error anymore?

Thanks again!

**Comment by izzycsy** [comment] 2021-07-09 08:50
Hi @saibot600 , glad it's resolved, to answer your questions: 

1. Yes, it's advised. Sometimes users face some issues. And having additional backups resolves the problems most of the time. A example of when to backup could be before an app update.
2. What automatic backup are you using? It could be possible that was the cause but we can't determine since we don't have the logs. Other causes could be old hardware, user went to rename/move the wallet.dat when app is running, etc. 
3. Sure, you can send it over so we can understand, but for your unique case, the solution is to find a working wallet.dat.
4. It's up to you, but please create a new backup and keep it safe. You might want to stick to the normal way of creating a backup.  

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/125051570-a83a9700-e0d5-11eb-9adf-867f1dfa8464.png">

<img width="1018" alt="Select folder to backup wallet1" src="https://user-images.githubusercontent.com/65014479/125051593-ae307800-e0d5-11eb-9dec-4542f492bb05.png">

<img width="1021" alt="Select folder to backup wallet2" src="https://user-images.githubusercontent.com/65014479/125051604-b12b6880-e0d5-11eb-9d72-e4915c4800ad.png">

**Comment by saibot600** [comment] 2021-07-16 20:35
Thanks a lot again. To address your points:

2.) From all the points you mentioned it can only be the backup solution in my case. I am using PCloud and have experienced some other similar file corruptions on files that I or some programs were using at the time PCloud was trying to back them up.

3.) I didn't create logs while I had the problem but only afterwards. Does that still help? If so, I would be a bit hesitant to just upload everything here publicly. Not sure how sensitive that info might be in the worst case.

**Comment by izzycsy** [comment] 2021-07-18 19:08
Hi @saibot600 , we do not support any other platform you decide to use, we can only help figure out if you've an issue and what went wrong and work from there. I'd suggest that you backup your wallet the conventional way to prevent the same thing from happening. I'll be closing your issue. Thank you.

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/126079335-c31ef81c-f9a0-4ef2-8d86-ccc936d81c90.png">

**Closed by izzycsy** 2021-07-18 19:08 UTC
Labels: kind/bug, needs/triage, os/win, version/2.5.2
