### ISSUE TITLE
Swapping DFI / USDT & DFI / ETH always get error

### ISSUE THREAD

**Issue by lezfez** [DeFiCh/app#319] opened 2021-01-16 22:54 UTC
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 2.1.10
- **Previous DeFi App Version:**
  - 2.1.9
- **Operating System (OS):**
  - macOS 10.15.7

### Screenshot(s) / screen recording(s) of issue

<img width="678" alt="AppIssue20210116-233526" src="https://user-images.githubusercontent.com/2002857/104824819-9d552700-5855-11eb-8a5f-496dcf546679.png">

### Actual Behavior

When swapping DFI and USDT I always get this error message. 

### App log / binary log / app config

# LOG:
`
[2021-01-16 23:34:01.893] [IPC-RENDERER-error]  Error: Request failed with status code 500`

**Comment by MrStryker** [comment] 2021-01-17 05:25
Duplicate of #315

**Comment by izzycsy** [comment] 2021-01-17 10:41
Hi @lezfez , thanks for your feedback 	, regarding the issue `DEX: Something went wrong`, I'll link you to <https://github.com/DeFiCh/app/issues/280> which we can further discuss on the problem. We would like to keep same issues in one thread. Thank you. 

Hi again @MrStryker , to you as well. Thank you.

**Closed by izzycsy** 2021-01-17 10:41 UTC
